### ISSUE TITLE
drm format modifiers  again

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#103]
Hi

on a intel system your query for the drm format modifiers is wrong.  It returns only intel format modifieres for r8 and r16 format. 
Here a patch to show you what is wrong with your query. In  src/opengl/formats.c I made the following change:

...
    fmt->glsl_type = pl_var_glsl_type_name(pl_var_from_fmt(fmt, ""));
    fmt->glsl_format = pl_fmt_glsl_format(fmt, fmt->num_components);
    fmt->fourcc = pl_fmt_fourcc(fmt);
    **if (fmt->fourcc == 0x38384752)       // RG88
               fmt->fourcc = 0x38385247;     // GR88
    if (fmt->fourcc == 0x32334752)       // RG32
               fmt->fourcc = 0x32335247;     // GR32**
    pl_assert(fmt->glsl_type);
....

 
Then I get also intel format modifiers for these formats.

debug:     NAME       TYPE   SIZE COMP CAPS         EMU DEPTH         HOST_BITS     GLSL_TYPE  GLSL_FMT   FOURCC
debug:     r8         UNORM  1    R    SsLRbBV--HWG n   {8  0  0  0 } {8  0  0  0 } float      r8         R8    
debug:         modifiers[0]: INVALID
debug:         modifiers[1]: LINEAR
debug:         modifiers[2]: INTEL 0x1
debug:         modifiers[3]: INTEL 0x2
debug:     rg8        UNORM  2    RG   SsLRbBV--HWG n   {8  8  0  0 } {8  8  0  0 } vec2       rg8        GR88  
debug:         modifiers[0]: INVALID
debug:         modifiers[1]: LINEAR
debug:         modifiers[2]: INTEL 0x1
debug:         modifiers[3]: INTEL 0x2
debug:     rgba8      UNORM  4    RGBA SsLRbBV--HWG n   {8  8  8  8 } {8  8  8  8 } vec4       rgba8      RA24  
debug:         modifiers[0]: INVALID
debug:         modifiers[1]: LINEAR
debug:     r16        UNORM  2    R    SsLRbBV--HWG n   {16 0  0  0 } {16 0  0  0 } float      r16        R16   
debug:         modifiers[0]: INVALID
debug:         modifiers[1]: LINEAR
debug:         modifiers[2]: INTEL 0x1
debug:         modifiers[3]: INTEL 0x2
debug:     rg16       UNORM  4    RG   SsLRbBV--HWG n   {16 16 0  0 } {16 16 0  0 } vec2       rg16       GR32  
debug:         modifiers[0]: INVALID
debug:         modifiers[1]: LINEAR
debug:         modifiers[2]: INTEL 0x1
debug:         modifiers[3]: INTEL 0x2
debug:         modifiers[4]: INTEL 0x4

****

**Comment by haasn** [comment]
I think we discussed this before but I forgot the specifics, remind me why you can't just use 'gr8' instead of 'rg8'?

**Comment by jojo61** [comment]
I can use gr8 or rg8 but the problem is somewhere else. You do not Query GR88 format modifier and also not offer the GLSL format  gr8. But the intel egl implementation seems to support only GR88 with Intel modifier. Also you do check in gpu.c with check_mod if the format modifier is available. You once changed  that to a warning but changed it back to a failure. So I need the intel format modifier for rg8 to pass the test in check_mod.  gr8 would also be fine but is not queried in src/opengl/formats.c at all.

That was the reason why I made the change to query RG88 for rg8 format to get a valid intel format modifier.
Same for GR32 (rg16) format.

I hope you do understand my layman wording.

**Comment by haasn** [comment]
Oh, I see the problem now. The issue is that there's no opengl implementation of `gr8`, the way there is for e.g. vulkan?

**Comment by haasn** [comment]
@jojo61 Hmm, investigating, I once again came to the conclusion that 'gr8' doesn't actually exist in either EGL or Vulkan, so I don't know how you *could* safely import these dmabufs. Can you remind me where you get your GR88 buffers from, and if it would be possible to get them as RG88 instead?

**Comment by haasn** [comment]
It's possible that it's supposed to "just work" when importing a GR88 buffer as an RG88 texture, but frankly I'm not sure *how* that's expected to work, given that the two have totally different internal representation. I think that even with the above hack, it should result in wrong rendering, no?

**Comment by haasn** [comment]
@jojo61 Does this patch make it work for you? https://code.videolan.org/videolan/libplacebo/-/commit/5429a538cc7000527a582258901650d7b0ddac53

I have no idea if this is even remotely reasonable, and it wouldn't work on Vulkan either way.

**Comment by jojo61** [comment]
Hi
this does not work. I think i have to explain a bit more in detail what I try to do.
I want to dma upload a YUV frame to a pl_texture. For the Y part I use r8 Format and for the UV Part I use rg8 Format.
When calling pl_tex_create you check for a valid drm format modifier against your internal table with the choosen format.
When you create this table you query with eglQueryDmaBufModifiersEXT and the fourcc Code for this format.
The Result is:
debug: GPU texture formats:
debug:     NAME       TYPE   SIZE COMP CAPS         EMU DEPTH         HOST_BITS     GLSL_TYPE  GLSL_FMT   FOURCC
debug:     r8         UNORM  1    R    SsLRbBV--HWG n   {8  0  0  0 } {8  0  0  0 } float      r8         R8
debug:         modifiers[0]: INVALID
debug:         modifiers[1]: LINEAR
debug:         modifiers[2]: INTEL 0x1
debug:         modifiers[3]: INTEL 0x2
debug:     rg8        UNORM  2    RG   SsLRbBV--HWG n   {8  8  0  0 } {8  8  0  0 } vec2       rg8        RG88
debug:         modifiers[0]: INVALID
debug:         modifiers[1]: LINEAR
debug:     rgba8      UNORM  4    RGBA SsLRbBV--HWG n   {8  8  8  8 } {8  8  8  8 } vec4       rgba8      RA24
debug:         modifiers[0]: INVALID
debug:         modifiers[1]: LINEAR
debug:     r16        UNORM  2    R    SsLRbBV--HWG n   {16 0  0  0 } {16 0  0  0 } float      r16        R16
debug:         modifiers[0]: INVALID
debug:         modifiers[1]: LINEAR
debug:         modifiers[2]: INTEL 0x1
debug:         modifiers[3]: INTEL 0x2
debug:     rg16       UNORM  4    RG   SsLRbBV--HWG n   {16 16 0  0 } {16 16 0  0 } vec2       rg16       RG32
debug:         modifiers[0]: INVALID
debug:         modifiers[1]: LINEAR

As you can see the format rg8 (RG88) has no Intel modifier and will be rejected by pl_tex_create in function check_mod()
So we need a intel format modifier for rg8. Surprisingly there is a intel format modifier for gr8 (GR88). So if we query the modifiers for format rg8 with fourcc GR88 then we get a valid intel format modifier and pl_tex_create works fine. See also my first post with the query results when I query with GR88 and GR32. 
Obviously the intel format modifier for RG88 and RG32 is missing in eglQueryDmaBufModifiersEXT. 
Fortunately it seems that intel handles rg8 and gr8 the same way and the dma works as expected.

So we do not need an artificial gr8 format, but just need to query the format modifiers for rg8  with GR8 and for reg16 with GR32 instead of RG8 and RG32.

**Comment by haasn** [comment]
> So we do not need an artificial gr8 format, but just need to query the format modifiers for rg8 with GR8 and for rg16 with GR32 instead of RG8 and RG32.

This sounds like a bug in the intel driver, then. If it accepts `rg8` textures with those modifiers and they work, it should also expose them in the list of modifiers.

I'll try and submit an intel driver patch for this instead, but I can merge a work-around into libplacebo in the meantime. (Though upstream might have its own opinions on what's correct)

**Comment by jojo61** [comment]
It seems  that upstream is slow :-)
Could you please provide a work-around in libplacebo.  Otherwise the current Version is unusable for me and my application.

**Comment by haasn** [comment]
Sorry, forgot about this, never took it upstream. I checked against the AMD implementation and it seems that AMD has the same issue of treating rg8 as GR88 internally. I'll implement a work-around.

**Comment by haasn** [comment]
Just to confirm, this works around it, correct?

```patch
diff --git a/src/gpu.c b/src/gpu.c
index fcb7d85..e55dec2 100644
--- a/src/gpu.c
+++ b/src/gpu.c
@@ -443,11 +443,9 @@ static const struct pl_fmt_fourcc pl_fmt_fourccs[] = {
     // 16 bpp red
     {"r16",         FOURCC('R','1','6',' ')},
     // 16 bpp rg
-    {"rg8",         FOURCC('R','G','8','8')},
-    {"gr8",         FOURCC('G','R','8','8')},
+    {"rg8",         FOURCC('G','R','8','8')}, // inverted, as per common practice
     // 32 bpp rg
-    {"rg16",        FOURCC('R','G','3','2')},
-    {"gr16",        FOURCC('G','R','3','2')},
+    {"rg16",        FOURCC('G','R','3','2')}, // inverted, as per common practice
     // 8 bpp rgb: N/A
     // 16 bpp rgb
     {"argb4",       FOURCC('A','R','1','2')},
```

**Comment by haasn** [comment]
In particular, I have no idea if ^ breaks vulkan or not...

**Comment by jojo61** [comment]
I can confirm that this will work.   I testet with the vulkan Version and the opengl Version of libplacebo.

**Comment by haasn** [comment]
Looking into it more it seems that, actually, *all* of our fourcc modifiers need to be swapped, because DRM fourcc uses the exact opposite memory order convention as libplacebo.
