### ISSUE TITLE
Fail to package 3.120.3

### ISSUE THREAD

**Issue by bl4ckb0ne** [haasn/libplacebo#104]
Hi there, I'm currently updating the libplacebo package in Alpinelinux (musl-libc based), and I'm encountering errors when running the tests on 3.120.3 with the vulkan headers and loader from `1.2.184`, glslang `11.5.0` and shaderc `2021.1`

```
[0.446][e] GL: GL_INVALID_OPERATION in glBufferData                             
[0.446][e] Failed importing host pointer!                                                                                       
=== FAILED: 'buf' at ../src/tests/gpu_tests.h:1370

[...]

[2.909][e] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
=== FAILED: 'buf' at ../src/tests/gpu_tests.h:1370

[...]

Summary of Failures:

10/11 opengl_surfaceless.c FAIL            0.62s   exit status 1
 9/11 vulkan.c             FAIL            3.24s   exit status 1
```

Same errors with `master`

```

[0.326][e] GL: GL_INVALID_OPERATION in glBufferData                             
[0.326][e] Failed importing host pointer!                                       
=== FAILED: 'buf' at ../src/tests/gpu_tests.h:1419

[...]

[0.010][w] API debugging requested but no debug meta layers present... ignoring
../src/amd/vulkan/radv_device.c:6504: FINISHME: Illegal color

../src/amd/vulkan/radv_meta_clear.c:390: FINISHME: color clears incomplete
[2.693][e] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:860)

[...]

Summary of Failures:

 9/11 opengl_surfaceless.c FAIL            0.40s   exit status 1
11/11 vulkan.c             FAIL            2.97s   exit status 1
```

But this time with the `Illegal color` issue

**Comment by haasn** [comment]
I get the `FINISHME` as well and as far as I can tell it's inconsequential, the clearing there is done in between tests. I assume the relevant bit is "failed importing host pointer", which seems to be the issue on both Vulkan and OpenGL.

In the full log, do you get any warning about non-page-aligned pointers?

**Comment by haasn** [comment]
Also, is this ANV or RADV? (Can you just post a full log?)

**Comment by bl4ckb0ne** [comment]
Here's both logs

[tests.3.120.3.log](https://github.com/haasn/libplacebo/files/6865512/tests.3.120.3.log)
[tests.master.log](https://github.com/haasn/libplacebo/files/6865514/tests.master.log)

There's indeed a mention of non-page aligned pointer in the first log on line 2160 (crashing GL test) and 12598 (crashing VK test). Same on the master log (line 1963 and line 13117).

This is RADV (RX 580) with mesa 21.1.5

**Comment by haasn** [comment]
That's certainly odd. The test in question uses `aligned_alloc` with an alignment of `0x1000`, which matches the `align_host_ptr` value reported by your GPU (`4096`). So the fact that it still triggers the warning would seem to imply that the result of `aligned_alloc` was not, in fact, aligned.

Can you verify it using this diff? If it fails on the alignment check, then this is not a libplacebo bug.

```diff
diff --git a/src/tests/gpu_tests.h b/src/tests/gpu_tests.h
index c2704b7..2bcd01f 100644
--- a/src/tests/gpu_tests.h
+++ b/src/tests/gpu_tests.h
@@ -1400,7 +1400,10 @@ static void pl_test_host_ptr(pl_gpu gpu)
     const size_t offset = 2 << 10;
     const size_t slice = 2 << 16;
 
-    uint8_t *data = aligned_alloc(0x1000, size);
+    size_t alignment = PL_MIN(gpu->limits.align_host_ptr, sizeof(void *));
+    uint8_t *data = aligned_alloc(alignment, size);
+    REQUIRE(((uintptr_t) data & ~(alignment - 1)) == (uintptr_t) data);
+
     for (int i = 0; i < size; i++)
         data[i] = (uint8_t) i;
 
```

**Comment by haasn** [comment]
(That said, it's still weird that it fails on the host pointer import even after manually forcing the alignment)

**Comment by bl4ckb0ne** [comment]
Failing on the same place, nothing from the alignment check.

**Comment by haasn** [comment]
@bl4ckb0ne Hmm. Can you post a log with this patch applied? (Replaces the previous)

```diff
diff --git a/src/gpu.c b/src/gpu.c
index fcb7d85..43ee2bf 100644
--- a/src/gpu.c
+++ b/src/gpu.c
@@ -981,7 +981,7 @@ pl_buf pl_buf_create(pl_gpu gpu, const struct pl_buf_params *pparams)
                             "but may cause issues in some rare circumstances.");
                 }
 
-                PL_TRACE(gpu, "Rounding imported host pointer %p + %zu -> %zu to "
+                PL_INFO(gpu, "Rounding imported host pointer %p + %zu -> %zu to "
                          "nearest page boundaries: %p + %zu -> %zu",
                           shmem->handle.ptr, shmem->offset, shmem->size,
                           (void *) ptr_base, buf_offset, ptr_size);
diff --git a/src/tests/gpu_tests.h b/src/tests/gpu_tests.h
index c2704b7..8ee457b 100644
--- a/src/tests/gpu_tests.h
+++ b/src/tests/gpu_tests.h
@@ -1400,10 +1400,14 @@ static void pl_test_host_ptr(pl_gpu gpu)
     const size_t offset = 2 << 10;
     const size_t slice = 2 << 16;
 
-    uint8_t *data = aligned_alloc(0x1000, size);
+    size_t alignment = PL_MAX(gpu->limits.align_host_ptr, sizeof(void *));
+    uint8_t *data = aligned_alloc(alignment, size);
+    REQUIRE(((uintptr_t) data & ~(alignment - 1)) == (uintptr_t) data);
+
     for (int i = 0; i < size; i++)
         data[i] = (uint8_t) i;
 
+    printf("testing import of host pointer %p\n", data);
     pl_buf buf = pl_buf_create(gpu, &(struct pl_buf_params) {
         .type = PL_BUF_TEX_TRANSFER,
         .size = slice,
diff --git a/src/vulkan/malloc.c b/src/vulkan/malloc.c
index 0d2540f..fbc9070 100644
--- a/src/vulkan/malloc.c
+++ b/src/vulkan/malloc.c
@@ -189,7 +189,7 @@ static void slab_free(struct vk_ctx *vk, struct vk_slab *slab)
 #endif
             break;
         case PL_HANDLE_HOST_PTR:
-            PL_TRACE(vk, "Unimporting slab of size %zu from ptr: %p",
+            PL_INFO(vk, "Unimporting slab of size %zu from ptr: %p",
                      (size_t) slab->size, (void *) slab->handle.ptr);
             break;
         }
@@ -891,7 +891,7 @@ static bool vk_malloc_import(struct vk_malloc *ma, struct vk_memslice *out,
         fdinfo.fd = -1;
         break;
     case PL_HANDLE_HOST_PTR:
-        PL_TRACE(vk, "Imported %zu of memory from ptr: %p%s",
+        PL_INFO(vk, "Imported %zu of memory from ptr: %p%s",
                  (size_t) slab->size, shmem->handle.ptr,
                  params->ded_image ? " (dedicated" : "");
         slab->handle.ptr = ptrinfo.pHostPointer;
```

**Comment by bl4ckb0ne** [comment]
[log.txt](https://github.com/haasn/libplacebo/files/6879482/log.txt)
There you go

**Comment by haasn** [comment]
Oh, I see. The warnings about a mis-aligned pointer come from a different part of the test framework, where such failures are expected/negligible. It doesn't come from the actual aligned import test. That pointer definitely conforms to the page alignment requirements advertised by the driver.

So it seems there's no bug in libplacebo here - something or other about your system is causing the graphics driver to fail on what appears to me a legitimate memory import operation. I don't think there's an actionable fix here from our side other than perhaps simply temporarily disabling that part of the test framework, maybe only on your platform? I would also suggest trying to take this up with mesa, since they advertise support for host pointers but then seemingly fail importing any host memory.

**Comment by bl4ckb0ne** [comment]
I'll deactivate the tests in the meantime and go hunt the bug in mesa, thanks for your time!

**Comment by bl4ckb0ne** [comment]
Hm, could the bug be linked to the new version of the VK headers? I tracked down the return value in the radv driver and the func seems pretty straightforward.

https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/amd/vulkan/radv_device.c#L2657

Maybe something changed in the enum in the header?

**Comment by haasn** [comment]
It's the `vkAllocateMemory` call which fails, the function you linked passes. If I had to guess, I'd say you're most likely executing until [this line](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/amd/vulkan/radv_device.c#L5377).

I'm not sure what enum change would cause this, and your theory also wouldn't explain why it also fails for OpenGL. Most likely the common denominator here is in the radeonsi memory importing code.
