### ISSUE TITLE
Regarding building.

### ISSUE THREAD

**Issue by ScradOWO** [haasn/libplacebo#113]
Ever since the new Dolby Vision commit I see a new runtime dependency was added, dovi, might be dumb of me so pardon but where does one acquire the said dependency from? 
The system being used to build is archlinux.

**Comment by haasn** [comment]
It's from [here](https://github.com/quietvoid/dovi_tool/tree/main/dolby_vision).

I recommend not worrying about it to be honest, it's mostly for testing and only affects `plplay`, not libplacebo itself.
