### ISSUE TITLE
Regarding custom_shader_path usage

### ISSUE THREAD

**Issue by redbaty** [haasn/libplacebo#117]
Hey, I have a question regarding the usage of multiple shaders with FFMpeg, I've been trying to use the following command:

`
fmpeg.exe -init_hw_device cuda=cuda:0 -filter_hw_device cuda -i ./input.mkv -filter_complex "[0:v]hwupload=derive_device=vulkan,libplacebo=w=3840:h=2160:custom_shader_path=shaders/Anime4K_Clamp_Highlights.glsl:custom_shader_path=shaders/Anime4K_Restore_CNN_Light_VL.glsl:custom_shader_path=shaders/Anime4K_Upscale_CNN_x2_L.glsl:custom_shader_path=shaders/Anime4K_AutoDownscalePre_x4.glsl:custom_shader_path=shaders/Anime4K_Restore_CNN_Moderate_M.glsl:custom_shader_path=shaders/Anime4K_Upscale_CNN_x2_M.glsl:custom_shader_path=shaders/Anime4K_Restore_CNN_Moderate_S.glsl:disable_builtin=true,hwupload=derive_device=cuda[s0]" -map "[s0]" -map "0:a" -c:v h264_nvenc -rc vbr -cq 24 -qmin 24 -qmax 24 -t 00:02:00 -y ./4k.mp4
`

but repeating :custom_shader_path= doesnt seem to be working, is there a syntax for multiple shaders like mpv's?

**Comment by haasn** [comment]
Unfortunately, no. What you can do is `cat` them into a single file and load that path. I agree that this should probably be supported, though. I'll look into it sometime. But, this is an FFmpeg bug, so strictly speaking off-topic here.

**Comment by redbaty** [comment]
Yeah I guess this makes more sense over at FFmpeg, but anyway even merging the shaders into one, it seems it haves no effect on the ouput file, some screenshots:

MPV running with `mpv --no-config --glsl-shaders="shaders/main.glsl" .\input.mkv`

![mpv-shot0001](https://user-images.githubusercontent.com/4898202/147013040-4e85a40d-2689-4c2e-ba9b-b8447540aa4a.jpg)

FFMpeg running with `.\ffmpeg.exe -init_hw_device cuda=cuda:0 -filter_hw_device cuda -i ./input.mkv -filter_complex "[0:v]hwupload=derive_device=vulkan,libplacebo=w=3840:h=2160:custom_shader_path=shaders/main.glsl,hwdownload,format=yuv420p[s0]" -map "[s0]" -map "0:a" -c:v hevc_nvenc -rc vbr -cq 24 -qmin 24 -qmax 24 -profile:v main10 -pix_fmt p010le -t 00:00:30 ./4k_265.mkv`

![mpv-shot0002](https://user-images.githubusercontent.com/4898202/147013176-5bb48e90-fad3-4f1c-982e-69f7277928e9.jpg)

FFMpeg with scale filter only (`ffmpeg -i .\input_short.mkv -vf scale=3840:2160 input_scaled.mkv`): 

![mpv-shot0006](https://user-images.githubusercontent.com/4898202/147013245-5dc72729-1a00-4a25-a212-351694c3b42b.jpg)

**Comment by redbaty** [comment]
It seems it can be an incompatibility between Anime4K and libplacebo, since running mpv with vo=gpu-next also produces no changes from the original file

**Comment by redbaty** [comment]
Found the solution over at https://github.com/bloc97/Anime4K/issues/144#issuecomment-991957519

**Comment by couleurm** [comment]
Hey, regarding the use of `custom_shader_path`, is there a way to specify literal path? I tried escape characters, normal and double quotes, double and normal backslashes, etc.. 
My -vf flag:
`-vf format=yuv420p,hwupload,"libplacebo=w=-2:h=2160:custom_shader_path='C:\Users\Dek\AppData\Roaming\Microsoft\Windows\SendTo\FSRCNNX_x2_16-0-4-1.glsl'",hwdownload,format=yuv420`

Works just fine when using relative dir
