### ISSUE TITLE
log.c execinfo support on *BSD

### ISSUE THREAD

**Issue by brad0** [haasn/libplacebo#118]
I noticed with libplacebo 4.192.0 there is now code in log.c using the backtrace / backtrace_symbols functions. For FreeBSD / NetBSD / OpenBSD and DragonFlyBSD the libexecinfo (which is in the base OS) library needs to be linked in.

**Comment by brad0** [comment]
Looking around I noticed this is also relevant for musl-based Linux OS's since musl doesn't have said functionality and uses the same libexecinfo from NetBSD.

**Comment by haasn** [comment]
@brad0 do you have a suggestion for how to best detect for this case in `meson.build`?

**Comment by haasn** [comment]
```diff
diff --git a/src/meson.build b/src/meson.build
index 2798e0ba..dd2f1fe0 100644
--- a/src/meson.build
+++ b/src/meson.build
@@ -69,10 +69,13 @@ if d3d11_found
 endif
 
 unwind = dependency('libunwind', required: get_option('unwind'))
+has_execinfo = cc.has_header('execinfo.h')
 conf_internal.set('PL_HAVE_UNWIND', unwind.found())
-conf_internal.set('PL_HAVE_EXECINFO', cc.has_header('execinfo.h'))
+conf_internal.set('PL_HAVE_EXECINFO', has_execinfo)
 if unwind.found()
   build_deps += [unwind, cc.find_library('dl', required : false)]
+elif has_execinfo
+  build_deps += cc.find_library('execinfo', required: false)
 endif
 
 # work-arounds for glslang braindeath
```

does this work?

**Comment by brad0** [comment]
I was just staring at the code trying to figure that  out but you beat me to it. Let me test that out and get back to you in a few seconds.

**Comment by brad0** [comment]
Thanks. That does the trick.
