### ISSUE TITLE
Mis-alignment of data when using NDEBUG

### ISSUE THREAD

**Issue by gbooker** [haasn/libplacebo#130]
When compiling with `NDEBUG`, the alignment of data allocated via `pl_zalloc` is not going to be 16-byte aligned.  This stems from:
https://github.com/haasn/libplacebo/blob/19aee6c4b40724527bce1ff88fcfaa06c61bea79/src/pl_alloc.c#L20-L31
With `NDEBUG` set, the alignment of `data` will not match the 16-byte alignment of the `header`.

This becomes an issue in this block of code:
https://github.com/haasn/libplacebo/blob/18f08b3d5790ef903458164c5f6c6b765523cd11/src/d3d11/gpu_pass.c#L834-L839

Because `struct pl_pass_d3d11` includes `struct struct d3d_num_workgroups_buf` which is defined:
https://github.com/haasn/libplacebo/blob/ca97575037d6a352c5d857797b2cd107452b753a/src/d3d11/gpu.h#L161-L163
this makes both structs require 16-byte alignment.  Due to that, the compiler is able to use instructions that require 16-byte alignment in zeroing out the other structure fields in the line: 
https://github.com/haasn/libplacebo/blob/18f08b3d5790ef903458164c5f6c6b765523cd11/src/d3d11/gpu_pass.c#L837-L839
In particular, it uses:
```
xorps       xmm6,xmm6  
movaps      xmmword ptr [r15+150h],xmm6
movaps      xmmword ptr [r15+160h],xmm6
…
```

This throws a CPU exception when the address is not 16-byte aligned.

While this may not be the best solution to the problem, we were able to work around via:
```diff
diff --git a/src/pl_alloc.c b/src/pl_alloc.c
index 4fb343b..4a695ac 100644
--- a/src/pl_alloc.c
+++ b/src/pl_alloc.c
@@ -27,7 +27,7 @@ struct header {
     struct ext *ext;

     // Pointer to actual data, for alignment purposes
-    intmax_t data[];
+    alignas(sizeof(float[4])) intmax_t data[];
 };

 // Lazily allocated, to save space for leaf allocations and allocations which
```

**Comment by haasn** [comment]
How about this?

```diff
commit a83d59a75f560ff326ed9c4ce87180728808e6d0
Author: Niklas Haas <git@haasn.dev>
Date:   Tue Jul 5 22:26:48 2022 +0200

    alloc: fix pl_alloc alignment
    
    intmax_t is not enough to guarantee alignment, we need max_align_t.
    
    Fixes https://github.com/haasn/libplacebo/issues/130

diff --git a/src/pl_alloc.c b/src/pl_alloc.c
index 4fb343bf..9731b8f3 100644
--- a/src/pl_alloc.c
+++ b/src/pl_alloc.c
@@ -27,7 +27,7 @@ struct header {
     struct ext *ext;
 
     // Pointer to actual data, for alignment purposes
-    intmax_t data[];
+    max_align_t data[];
 };
 
 // Lazily allocated, to save space for leaf allocations and allocations which
```

That aligns to 32 bytes on my system. We already use `max_align_t` in the alignment code for `PL_PRIV`, so there's really no reason to avoid using it here.

**Comment by haasn** [comment]
`max_align_t` is *already* specified to be a type that aligns to the maximum alignment requirement - so specifying the field as `max_align_t` is redundant with `alignas(max_align_t)`.

**Comment by gbooker** [comment]
Yeah, I initially misread your patch thinking it was `max_align_t intmax_t data[];` which obviously doesn't work.  I tested the patch as you wrote it and it does work.

**Comment by rcombs** [comment]
Please note that this won't work on 32-bit Win32, where malloc is 8-byte-aligned instead of 16; also, I'm not sure if max_align_t is 16-byte on windows or not (I thought it was 8?).

Is there a reason for d3d_num_workgroups_buf to be over-aligned in the first place?
