### ISSUE TITLE
Error with Vulkan on Intel GPU with Linux Kernel 5.16+

### ISSUE THREAD

**Issue by gitpubber** [haasn/libplacebo#135]
Hello @haasn , 
I am having important error. whenever i try to play any media file using vulkan renderer(both wayland and x11), it throws this error (maybe suddenly or after playing few frames). 
![image](https://user-images.githubusercontent.com/86718962/183690905-04bc5436-f504-4432-9fa0-b7ca9050efb1.png)

The error originates at:
https://github.com/haasn/libplacebo/blob/eeab271b4871c1639c961243c19d6761835463c2/src/vulkan/command.c#L382 and
https://github.com/haasn/libplacebo/blob/eeab271b4871c1639c961243c19d6761835463c2/src/vulkan/gpu.c#L111

The error is caused due to failed assertions.

I face this error on latest kernels(5.16+. currently am on 5.19) only. If i switch my kernel back to linux 5.15, I don't get these errors. I have tried different distros too and the same behaviour exists. I have tested with git variants of mesa, kernel and mpv and the same problem exists. Opengl renderer works fine and this is the problem with Vulkan renderer.

I have posted this bug report too fyi: https://github.com/mpv-player/mpv/issues/10425

Thank you for libplacebo!

**Comment by gitpubber** [comment]
https://0x0.st/o2KC.txt

Strace log

**Comment by 24fpsDaVinci** [comment]
can confirm, kernel 5.19.3 same problem

**Comment by 24fpsDaVinci** [comment]
i no longer have this issue with [v5.228.0-rc1](https://github.com/haasn/libplacebo/releases/tag/v5.228.0-rc1), it was most likely a user build error. intel xe gen 11

**Comment by haasn** [comment]
So can this be closed? @gitpubber

**Comment by gitpubber** [comment]
@haasn , I run Linux 6.x(default kernel of archlinux) and as of writing, i run into the same error.

Please see https://github.com/mpv-player/mpv/issues/10425 too.

https://gitlab.freedesktop.org/drm/intel/-/issues/6564#note_1501978 is the major source of this bug.

**Comment by 24fpsDaVinci** [comment]
i am having the same problem, happens frequently under hwdec=vaapi. does not happen with software decode. kernel 6.0

**Comment by kasper93** [comment]
I can confirm it is fixed by https://github.com/torvalds/linux/commit/3f882f2

**Comment by 24fpsDaVinci** [comment]
currently running 6.4 rc3, fedora 39, libplacebo master, mpv master. the issue appears fixed.
