### ISSUE TITLE
LUT generation became very slow somewhere between version v4.204.0 (API v204) and v4.206.0 (API v206)

### ISSUE THREAD

**Issue by CrHasher** [haasn/libplacebo#139]
There was some change in between these 2 versions that made 3DLUT generation way slower.

In the mpv logs I see this for a version v4.204.0 (API v204):
Spent 3115.000 ms generating ICC 3DLUT (slow!)

and with new version v4.206.0 (API v206):
Spent 86609.000 ms generating ICC 3DLUT (slow!)

**Comment by haasn** [comment]
How long does it take with `--vo=gpu` when you don't use the ICC cache? (Specifically for mpv versions including commit 81c5ed)

**Comment by CrHasher** [comment]
The message does not appear without `--vo=gpu` and no ICC cache. I can only see it takes mpv the same amount of time or even more to start playing the video.

**Comment by haasn** [comment]
Then this is expected.

The "slowdown" you are seeing is the result of a bug fix. In the past, the LUT was not generated correctly. This bug affected both `--vo=gpu` and `--vo=gpu-next`, which is why they are both slow now.

Support for ICC 3dlut caching is tracked [in this upstream issue](https://code.videolan.org/videolan/libplacebo/-/issues/205).

**Comment by CrHasher** [comment]
I see no difference in speed between using cache option and not using it (just tested it). It also makes mpv hang in most cases.

**Comment by haasn** [comment]
> I understand that LUT generation was not as expected but how did generation go from a few seconds to 1.5+ mins?

In older versions the 3DLUT size was effectively capped at 49x49x49.

**Comment by CrHasher** [comment]
> > I understand that LUT generation was not as expected but how did generation go from a few seconds to 1.5+ mins?
> 
> In older versions the 3DLUT size was _effectively_ capped at 49x49x49. If you set your 3dlut-size to that, it will be as fast as expected.

Makes total sense now I went back to default value of 64x64x64 fast and looks just fine anyway. Thanks for the info, have a nice day!
