### ISSUE TITLE
src/opengl/meson.build:7:4: ERROR: C shared or static library 'dl' not found

### ISSUE THREAD

**Issue by brad0** [haasn/libplacebo#147]
Trying to build libplacebo 5.229.1 on OpenBSD it currently fails like so..

OpenBSD does not have libdl, like FreeBSD and NetBSD.

```
../../pobj/libplacebo-5.229.1/libplacebo-5.229.1/src/opengl/meson.build:7:4: ERROR: C shared or static library 'dl' not found
```

**Comment by haasn** [comment]
Here is the check:

```
if host_machine.system() == 'windows'
    libdl = declare_dependency()
else
    libdl = cc.find_library('dl', required : opengl_link)
endif
```

Do you know how to correctly extend this check to the OpenBSD case? Also, it seems like you're only getting this as an error because you set `--Dgl-proc-addr=enabled`, is that the case?

**Comment by brad0** [comment]
> Here is the check:
> 
> ```
> if host_machine.system() == 'windows'
>     libdl = declare_dependency()
> else
>     libdl = cc.find_library('dl', required : opengl_link)
> endif
> ```
> 
> Do you know how to correctly extend this check to the OpenBSD case? Also, it seems like you're only getting this as an error because you set `--Dgl-proc-addr=enabled`, is that the case?

Ya, I came across that. I'll look into a patch.

I have not explicitly enabled anything.

**Comment by haasn** [comment]
Can you post your meson log? On my end even changing it from `'dl'` to `'skdjfksjdf'` it doesn't fail compilation - just disables that feature

**Comment by brad0** [comment]
[meson-log.txt](https://github.com/haasn/libplacebo/files/9945131/meson-log.txt)

**Comment by haasn** [comment]
Bizarre. Looks like a meson bug. I'll raise it with them.

**Comment by haasn** [comment]
Oh, it has a simple explanation:

From your log: `Build Options: ... -Dauto_features=enabled`

You (or somebody else) enabled a flag that forces all features to be enabled by default. That explains why it was hard-erroring on failing to find libdl.

**Comment by eli-schwartz** [comment]
You may also bump the minimum meson_version to 0.62.0, then use https://mesonbuild.com/Dependencies.html#dl-libdl which checks if the libc provides the dlopen functionality, as it does on OpenBSD.

The backwards-compatible method which meson will suggest you use if you try `dependency('dl')` without bumping the minimum, is:
> consider checking for `dlopen()` with and without `find_library('dl')`

but then you need to roll your own feature checks.

**Comment by haasn** [comment]
Upgrading the meson version sounds like the easiest solution moving forwards. Though for a backwards compatibility patch I would rather just blacklist OpenBSD from the check for now.
