### ISSUE TITLE
tone mapping

### ISSUE THREAD

**Issue by xiatutu** [haasn/libplacebo#151]
Hello，When I read the code in tone_mapping.c , I was confused about the implementation of the BT.2446 method A.

For SDR2HDR : bt2446a_inv function
The bt1886_oetf function handles SDR signals  following BT.709 colorimetry，but in BT2446 method A, the input is required to be SDR signals following BT.2020 colorimetry. 
Don't you need a conversion between bt709 and bt2020 here?

static void bt2446a_inv(float *lut, const struct pl_tone_map_params *params)
{
    FOREACH_LUT(lut, x) {
        x = bt1886_oetf(x, params->input_min, params->input_max);
        x *= 255.0;
        if (x > 70) {
            x = powf(x, (2.8305e-6f * x - 7.4622e-4f) * x + 1.2528f);
        } else {
            x = powf(x, (1.8712e-5f * x - 2.7334e-3f) * x + 1.3141f);
        }
        x = powf(x / 1000, 2.4f);
        x = rescale_out(x, params);
    }
}

The bt2446a:
The purpose of the method described in this section is to provide a baseline conversion taking as input
SDR signals following BT.2020 colorimetry that are intended to be displayed in a reference viewing
environment at 100 cd/m2. Signals using BT.709 colorimetry may also serve as input, albeit that they
should first be mapped or converted to use BT.2020 colorimetry.

**Comment by haasn** [comment]
BT.709 and BT.2020 have identical (SDR) tone response curves. [BT.2020](https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2020-2-201510-I!!PDF-E.pdf) references BT.1886.
