### ISSUE TITLE
Question: which color is correct

### ISSUE THREAD

**Issue by CharlesMengCA** [haasn/libplacebo#157]
Hi Haasn,

For this video https://www.demolandia.net/downloads.html?id=43254366

```
mpv "d:\Test Videos\dolby-vision-amaze-(dolby-vision)-(www.demolandia.net).mp4" --start=9.9% --frames=1 --pause
```

The colour of the flower is quite different between with and without libdovi. 

Could you check and let me know which one is rendered correctly? 

Thanks a lot!

mpv-without-libdovi
![mpv-without-libdovi](https://user-images.githubusercontent.com/58993776/220174078-749a25cf-a3d9-4536-a0b0-14cfd678ac1f.jpg)
mpv-libdovi
![mpv-libdovi](https://user-images.githubusercontent.com/58993776/220174076-cd235630-26e8-490d-a224-5de70b5e1542.jpg)

**Comment by haasn** [comment]
Second one looks much more correct to me. YMMV

**Comment by CharlesMengCA** [comment]
Thanks. :)
