### ISSUE TITLE
"Failed initializing vulkan device"

### ISSUE THREAD

**Issue by damian101** [haasn/libplacebo#159]
When running mpv with `--gpu-api=vulkan`, I get error messages:
```
[vo/gpu-next/libplacebo] Found no suitable device, giving up.
[vo/gpu-next/libplacebo] Failed initializing vulkan device
[vo/gpu-next] Failed initializing any suitable GPU context!
Error opening/initializing the selected video_out (--vo) device.
```
This issue is not exclusive to mpv, vs-placebo crashes too.
Everything worked fine until a few days ago, after a system update. 

Operating system: Arch Linux
libplacebo v5.229.1-317-g2dea081c

**Comment by haasn** [comment]
I need more information. Does `vulkaninfo` work? If no, probably an issue with your system.

**Comment by damian101** [comment]
> I need more information. Does `vulkaninfo` work? If no, probably an issue with your system.

Yes, vulkaninfo works fine, and various Vulkan compute applications too.

**Comment by haasn** [comment]
Then post a log made with `--log-file=mpv-sucks.log`

**Comment by damian101** [comment]
> Then post a log made with `--log-file=mpv-sucks.log`

[mpv-sucks-less.log](https://github.com/haasn/libplacebo/files/10910830/mpv-sucks-less.log)

**Comment by kasper93** [comment]
> Yes, vulkaninfo works fine, and various Vulkan compute applications too.

By working do you mean it detects only llvmpipe? (could you provide log?) libplacebo reject software implementations by default, as it doesn't really make sense to use them and you should rather fix your system to provide hardware accelerated vulkan.


```
[   0.639][v][vo/gpu-next/libplacebo] Probing for vulkan devices:
[   0.925][v][vo/gpu-next/libplacebo]     GPU 0: llvmpipe (LLVM 15.0.7, 256 bits) (software)
[   0.925][v][vo/gpu-next/libplacebo]            uuid: 6D:65:73:61:32:32:2E:33:2E:36:00:00:00:00:00:00
[   0.926][d][vo/gpu-next/libplacebo]       -> excluding due to !params->allow_software
[   0.926][f][vo/gpu-next/libplacebo] Found no suitable device, giving up.
[   0.926][f][vo/gpu-next/libplacebo] Failed initializing vulkan device
```

I could suggest using mpv's `--gpu-sw` if that's really what you want. But from quick check in the code it is only wired for opengl in mpv. You could report issue about this flag if you need it.
