### ISSUE TITLE
unknown option: prefer_static

### ISSUE THREAD

**Issue by seemantk** [haasn/libplacebo#162]
Hello, I'm trying to package this version for Funtoo Linux, and I am seeing this error.

`src/glsl/meson.build:28:2: ERROR: Tried to access unknown option "prefer_static".`

It might be related to: https://github.com/haasn/libplacebo/commit/1cb65071874fd446625d2563a62dde83f0d50f19

**Comment by seemantk** [comment]
thank you @kasper93 for this clarification.  Unfortunately for Funtoo, we have some challenges to update meson and so we have it pinned 0.59, so for now we'll pin our libplacebo to 0.226.2

**Comment by kasper93** [comment]
@seemantk: I forgot to mention last, time. While older versions of meson don't set this option to default value, causing the issue you observed. You can just `-Dprefer_static=false` to make it work.

**Comment by seemantk** [comment]
@kasper93 thank you so much.  Actually I filed this ticket because that option failed for me with 0.59
We're working on upgrading meson distro-wide on Funtoo, but there are a lot of edge cases so it's a slower process
