### ISSUE TITLE
About ABI / SO version changes

### ISSUE THREAD

**Issue by kwizart** [haasn/libplacebo#164]
It seems like libplacebo changes ABI very often, last version bumped from libplacebo.so.229 to libplacebo.so.264.
According to the version, the major should more likely to be libplacebo.so.5.

Is this expected to break ABI every release ?
Is it possible to reduce incompatibilities ? That will ease distro maintainer to update the library more often during stable upgrades...

Thanks for your insight with this.

**Comment by haasn** [comment]
We break ABI for every change to the external API, pretty much. It would be possible to reduce it, but only at the cost of sacrificing something else.

For the sake of release-basted distros, we maintain release branches where important/crucial bugfixes get backported without ABI break. (There will be a 5.264.1 soon, to address a critical regression in 5.264.0)
