### ISSUE TITLE
Q: DoVi P5 Color/dark details

### ISSUE THREAD

**Issue by aboulfad** [haasn/libplacebo#166]
Hello,

I have compiled git-latest for ffmpeg, libplacebo & mpv on macOS to give DoVi P5 a try. I am unsure if there are any options to specify with mpv aside from `--vo=gpu-next`. The colours look somewhat off as well the video is much darker, with much loss of shadow details. I understand this implementation is sort of "experimental" but wanted to double check I am not missing on some build or runtime options.

MPV Logs included in the gdrive [LINK](https://drive.google.com/drive/folders/16jf9hXlem0ICXXi5DQI67z4emifl7X7s?usp=sharing) with screenshots and Dolby reference P5 video. Top right is mpv, bottom left is Infuse Pro. Thank you.

**Comment by haasn** [comment]
Two notes:

1. This sample contains bad metadata, signalling a much higher peak than is actually present in the sample. There's an outstanding feature request to add an option to ignore/strip such metadata.
2. Your Infuse Pro sample seems to just be hard-clipping the clip. You can achieve this (or very similar) result with `--tone-mapping=clip`, or `--tone-mapping=bt.2390` for a less extreme version.

**Comment by aboulfad** [comment]
Thank you for you insight and confirming I am not missing any runtime options. Can you kindly reference those feature requests regarding 1 & 3 ? (if they are captured somewhere)

Re 1: This sample is direct from [Dolby Labs](https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/), could it be they included such metadata for unknown reasons. I guess you are referring to something in `vdr_dm_data` (RPU data), can you mention which ?

Re 2: If you check the brick around the fire in screenshot or video, you can see details while in mpv it's very dark and no details. BTW Quicktime 10.5 shows similar results as Infuse Pro 7.5, maybe they are using the same underlying whatever libs to decode DoVi P5. Tone mapping bt.2390 yield slightly more shadow details, thanks for those suggestions.

**Comment by haasn** [comment]
For dark details, maybe `--target-trc=gamma2.2` is a better fix than messing with the tone mapping? mpv assumes a bt.1886 calibration by default, but a lot of monitors also ship with something closer to a pure power curve, which would crush black detail if used to display bt.1886 content.

**Comment by aboulfad** [comment]
> For dark details, maybe `--target-trc=gamma2.2` is a better fix than messing with the tone mapping? mpv assumes a bt.1886 calibration by default, but a lot of monitors also ship with something closer to a pure power curve, which would crush black detail if used to display bt.1886 content.

Thank you, 2.2 didn't do much to shadow details, so far it seems tone mapping bt.2390 yields closer (but still dark) results to either QT or Infuse or my LG E7 OLED. I've been reading many discussions in GH for mpv & HDR, it's a complicated topic with varying results & moreso for DoVi P5.  I am glad to try any other suggestions, short of any please feel free to close this.
