### ISSUE TITLE
Vulkan.c Test fails

### ISSUE THREAD

**Issue by aboulfad** [haasn/libplacebo#167]
Hi,

Vulkan.c test fails, I also noticed the 2nd error reported by plplay which is super slow (unusable, many dropped frames) and defaults to software decoding even though hevc_videotoolbox is available. Thank you.

I traced the first error to _pl_texture_tests(_) -> _pl_test_roundtrip()_ for RGB8s which fails and this  `if (fmt->emulated && fmt->type == PL_FMT_FLOAT)`  (not that I understand any of it)

`=== FAILED: memcmp(src, dst, bytes) == 0 at ../src/tests/gpu_tests.h:199
at position 31: 0x80 != 0x81`

`[0.125][i] vk Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties2-format-parameter ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x46835167 | vkGetPhysicalDeviceFormatProperties2KHR: value of format (1000330001) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.243.0/mac/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties2-format-parameter)`

Software version:

- MacOS Ventura 13.3.1 (MacBook Pro 2018 i7 - Intel Iris Plus Graphics 655)
- mpv version: 0.35.1 (compiled using git tag)
- libplacebo version: v5.264.0 ((compiled using git tag))
- VulkanSDK: 1.3.243.0

[vulkaninfo.log](https://github.com/haasn/libplacebo/files/11302365/vulkaninfo.log)
[plplay.log](https://github.com/haasn/libplacebo/files/11302366/plplay.log)
[libplacebo-5.264.0-INSTALL.log](https://github.com/haasn/libplacebo/files/11302367/libplacebo-5.264.0-INSTALL.log)
[testlog.txt](https://github.com/haasn/libplacebo/files/11302368/testlog.txt)

**Comment by haasn** [comment]
> [0.093][i]     API version: 1.2.243

We now require vulkan 1.3, which includes the missing format complained about in the validation error (1000330001). So this bug should be fixed on master, assuming you upgrade your vulkan drivers to support vulkan 1.3 of course.

For the memcmp bug, that one is almost surely a driver bug - since we just upload and download the texture using `vkCmdCopyBufferToImage` and `vkCmdCopyImageToBuffer`, it absolutely shouldn't give us back a result that is off-by-one (0x80 vs 0x81, as in your log).

**Comment by aboulfad** [comment]
It seems (I know little about this) that the Max API version for any Apple based products is 1.2.243, at least based on querying this https://vulkan.gpuinfo.org/listdevices.php?platform=macos

Aside from that test failing, does that mean that some aspect of libplacebo using Vulkan doesn't work as intended ?

**Comment by haasn** [comment]
Okay, I will revert to vulkan 1.2 minimum ver

**Comment by aboulfad** [comment]
I’ve been searching but I can’t find out why Vulcan API ver is 1.2 for many Mac devices, probably because the underlying integrated graphic device(s) used. Windows/[Linux](https://vulkan.gpuinfo.org/listdevices.php?platform=linux) section from that same link shows 1.3 for many entries.

**Comment by haasn** [comment]
> I’ve been searching but I can’t find out why Vulcan API ver is 1.2 for many Mac devices, probably because the underlying integrated graphic device(s) used. Windows/[Linux](https://vulkan.gpuinfo.org/listdevices.php?platform=linux) section from that same link shows 1.3 for many entries.

It's because of MoltenVK being slow to update to vk 1.3. macOS has no native vulkan drivers.
