### ISSUE TITLE
Build Failed When Opengl Is Disabled

### ISSUE THREAD

**Issue by CharlesMengCA** [haasn/libplacebo#168]
Hi Haasn,

When Opengl was disabled, glad_dep is undefined in src/meson.build since it is defined in src/opengl/include/glad/meson.build

```
 dependencies: build_deps + glad_dep,
```

Could you take a look?

**Comment by haasn** [comment]
cc @kasper93

**Comment by kasper93** [comment]
Will fix shortly.
