### ISSUE TITLE
2 latest builds writing a libplacebo.cache file into the portable_config sub directory 

### ISSUE THREAD

**Issue by movieperson** [haasn/libplacebo#179]
2 latest builds (07/07 and 07/08) are writing a libplacebo.cache file into the portable_config sub directory which appears to cause frame drops and audio dropouts when the source audio is Dolby TrueHD.

The header of the file contains the following:
Microsoft (R) HLSL Shader Compiler 10.1

**Comment by haasn** [comment]
Wrong project's bug tracker. libplacebo has nothing to do with audio.

(P.s. on the mpv bug tracker you will be asked to provide a log.)

**Comment by movieperson** [comment]
Not an audio problem.  Why are the latest two builds writing this file in the first place?
