### ISSUE TITLE
Audio dropout issues on Atmos have returned, but only if I chapter skip or seek 

### ISSUE THREAD

**Issue by movieperson** [haasn/libplacebo#180]
mpv version: mpv-x86_64-20230709-git-fc3e28f
Windows Version: Win 10 Pro 22H2 19045.3086
Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild

When playing a BD or UHD disc with a Dolby ATMOS audio track selected and using bit-streaming, any seeks or chapter skips will cause intermittent audio dropouts. These do not occur immediately after the chapter skip or seek, but usually begin several minutes later and with varying frequency.

Playing the same disk without any seeks or chapter skips does not show this issue. I also don't believe that this occurs when bit-streaming is disabled.

The movie used for the attached log files was "Mamma Mia, Here We Go Again" although I have seen the same issues occur on many different Dolby ATMOS titles after I have performed a chapter skip or seek.

Atmos_audio_drops_no seek_chapters.txt was created by doing a complete showing of the movie with no user intervention.

Atmos_audio_drop_seeks_chapters.txt was created by starting the movie, then performing several chapter skips and also several timed seeks just after starting playback. Playback was ended after a few occurrences of the audio dropouts.

I attempted to report this  on the ffmpeg web site, but for some reason I have never received the verification mail, even after many attempts.  

I'm not sure if this is a reversion.

[Atmos_audio_drops_no.seek_chapters.txt](https://github.com/haasn/libplacebo/files/12014682/Atmos_audio_drops_no.seek_chapters.txt)
[Atmos_audio_drop_seeks_chapters.txt](https://github.com/haasn/libplacebo/files/12014686/Atmos_audio_drop_seeks_chapters.txt)

**Comment by haasn** [comment]
Again, libplacebo does not handle audio at all.
