### ISSUE TITLE
Specify tone-mapping-param value to use for auto selected TM algorithm

### ISSUE THREAD

**Issue by MidnightWatcher** [haasn/libplacebo#181]
@haasn - It appears that **tone-mapping-param** values are ignored if tone-mapping=auto. I have to specify **tone-mapping=spline** for example to adjust tone mapping parameters for spline, but I prefer to keep tone-mapping=auto and allow linplacebo to automatically select the best curve according to internal heuristics. Is there a way to specify what tone-mapping-param value to use for each algorithm if auto selected? If not, can this be added?

**Comment by haasn** [comment]
I will change the way tone mapping parameters work, I think. Need to think up a good new API.

**Comment by haasn** [comment]
Will be fixed by https://code.videolan.org/videolan/libplacebo/-/merge_requests/546

**Comment by haasn** [comment]
You can set them specifically now via `--libplacebo-opts`. I'm not yet sure if I want to map these to mpv, because I plan on changing them in the near future. Can this issue be closed?

**Comment by haasn** [comment]
Derp, I forgot this is a libplacebo issue and not an mpv issue. So yeah, from the libplacebo API side of things, this is definitely exposed now.
