### ISSUE TITLE
FPS Rate changes - display FPS: 29.963 ->30.075

### ISSUE THREAD

**Issue by CharlesMengCA** [haasn/libplacebo#184]
Hi haasn,

During comparing the log from different builds, I found the new mpv.exe changed the FPS rate from 29.963 to 30.075.

Is this correct? Please refer the following comparison screenshot.

![image](https://github.com/haasn/libplacebo/assets/58993776/e40b4156-ebd7-4cbd-aae8-38b071da6ef9)

Regards,

Charles

**Comment by haasn** [comment]
Probably the result of bf69a45a3dc27645391289ba5f72de7d82eecee0?

I wouldn't worry too much about it, this line is just a diagnostic printout. The linked commit makes libplacebo print it earlier than before.
