### ISSUE TITLE
No `vkGetInstanceProcAddr` function provided, and libplacebo built without linking against this function!

### ISSUE THREAD

**Issue by zshnb** [haasn/libplacebo#186]
hi i have some problems when using libplacebo
i compiled ffmpeg 6.0 with --enable-vulkan, --enable-libplacebo, but when i try to transcode a 10bit bt2020 video to 8bit bt709, the error message of title appeared, my ffmpeg command is

./ffmpeg -y -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 3 -i UPL_1vKBpdd4iX.mp4 -vf "hwupload=derive_device=vulkan,libplacebo=format=yuv420p10le:colorspace=bt709:color_primaries=bt709:color_trc=bt709,hwdownload,format=yuv420p" -c:v h264_nvenc -c:a copy "outputHLG.mp4"

my os is Ubuntu 20.04, vulkan version is Release 1.3.250

**Comment by haasn** [comment]
This should be set from `hwctx`, so I don't know how you can end up with this error path. Something doesn't add up - FFmpeg would have crashed if this pointer was unset.

**Comment by haasn** [comment]
Is there any chance you could step into the affected call `pl_vulkan_import` inside gdb and confirm that `params->get_proc_addr` is set?

**Comment by zshnb** [comment]
sorry i don't know how can i do this, can you give me some steps to do this?

**Comment by zshnb** [comment]
this is the vulkan issue? or libplacebo issue?

**Comment by zshnb** [comment]
and if i only use cpu to do like `./ffmpeg -y -i UPL_1vKBpdd4iX.mp4 -vf "libplacebo=format=yuv420p10le:colorspace=bt709:color_primaries=bt709:color_trc=bt709,format=yuv420p" -c:v libx264 -c:a copy "output709.mp4"`, also got same error message.

**Comment by zshnb** [comment]
i just fix this after  re-install all dependency in a new machine, i think the most important thing is install vulkan before install libplacebo, not re-install libplacebo after install vulkan.
