### ISSUE TITLE
use libplacebo with CUDA and hardware accelerate failed

### ISSUE THREAD

**Issue by zshnb** [haasn/libplacebo#187]
hi i want to use libplacebo, but the speed is too slow, less than 1x. so i want to use hw accelerate, so i try this command

`./ffmpeg -threads 1 -hwaccel cuda -hwaccel_output_format cuda -i UPL_0UOVszENQF.mp4 -vf "scale_cuda=interp_algo=bilinear,hwupload=derive_device=vulkan,libplacebo=colorspace=bt709:color_primaries=bt709:color_trc=bt709:format=yuv420p:upscaler=none:downscaler=none:peak_detect=0,hwupload=derive_device=cuda" -c:v h264_nvenc -y UPL_0UOVszENQF.libplacebo.cuda.mp4`

but i got these error
```
Impossible to convert between the formats supported by the filter 'Parsed_hwupload_1' and the filter 'auto_scale_0'
[vf#0:0 @ 0x55fdd3f4b5c0] Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while filtering: Function not implemented
[out#0/mp4 @ 0x55fdd3f255c0] Nothing was written into output file, because at least one of its streams received no packets.
```
could you please tell me how can i do this?
my ffmpeg is 6.0, CUDA is 12.2, os is ubuntu 20.04LTS

**Comment by haasn** [comment]
I don't know as I've never tried using CUDA, but if in doubt, try adding more `format` filters. Like `-vf format=cuda,...,hwupload=derive_device=vulkan,format=vulkan,libplacebo=...,format=vulkan,hwupload=derive_device=cuda,format=cuda`

that should at least help narroww down the issue

**Comment by zshnb** [comment]
> I don't know as I've never tried using CUDA, but if in doubt, try adding more `format` filters. Like `-vf format=cuda,...,hwupload=derive_device=vulkan,format=vulkan,libplacebo=...,format=vulkan,hwupload=derive_device=cuda,format=cuda`
> 
> that should at least help narroww down the issue

thank you, if i don't use CUDA, how can i speed up filter process? because use cpu is too slow.

**Comment by zshnb** [comment]
@haasn i'm sorry to bother you, i have test a lot command. i found some discussion:
![image](https://github.com/haasn/libplacebo/assets/17894980/63bd506e-c060-4702-a83e-bd03100c76d0)
in https://github.com/jellyfin/jellyfin-ffmpeg/issues/215, it seems the latest libplacebo doesn't support hw right?
so i compiled v5.229.2 libplacebo with vulkan 1.3.239 and test again, but i got this error:
libplacebo version v5.229.2 too old to import Vulkan device, remove it or upgrade libplacebo to >= 5.278
so in the conclude there are two problems
1. latest libplacebo doesn't support hw
2. downgrade 5.229.2 can't work with vulkan
i have no idea how to fix there two problem, could you please help me?

**Comment by haasn** [comment]
> in https://github.com/jellyfin/jellyfin-ffmpeg/issues/215, it seems the latest libplacebo doesn't support hw right?

Huh? This is the first I'm hearing of any such issue. I looked at the link bug report and that assertion should be impossible to hit, we test every possible pixfmt in libplacebo test framework. How can I reproduce this issue? Which pixel format are you using, exactly?

**Comment by zshnb** [comment]
> 

thanks for your reply, i'll give you the whole steps to reproduce it.
1. download this video: https://drive.google.com/file/d/1VOxzSwU38dM3Ntm1J3ny9Z0j0-uM3GOX/view?usp=sharing
2. make sure ffmpeg version is 6, libplacebo version is latest, vulkan version is 1.3.250
3. compile ffmpeg with cuda, vulkan, libplacebo
4. exec `./ffmpeg -y -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 3 -i UPL_0UOVszENQF.mp4 -vf "hwupload=derive_device=vulkan,libplacebo=format=yuv420p10le:colorspace=bt709:color_primaries=bt709:color_trc=bt709,hwdownload,format=yuv420p" -c:v h264_nvenc -c:a copy UPL_0UOVszENQF.libplacebo.cuda.mp4`

**Comment by zshnb** [comment]
and i have a vm with full environment, if you are unconvenient to build these component, i can provide vm to you for help test, if you need, we can discuss at some IM

**Comment by zshnb** [comment]
> I'll need to wait until I can access my nvidia GPU again before I can test. In the meantime it would help if you upgrade to ffmpeg 6.1 and libplacebo v6.292.1 and then provide a full log
@haasn ok, i'll test again and give you ffmpeg full trace log

**Comment by zshnb** [comment]
more question, ffmpeg 6.1 is its master branch? i only see 6.0release branch

**Comment by zshnb** [comment]
@haasn i try to build ffmpeg release/6.0 branch with libplacebo 6.292.1, but build failed, the error is below
libavfilter/vf_libplacebo.c: In function ‘process_frames’:
libavfilter/vf_libplacebo.c:388:13: warning: ‘PL_TONE_MAP_RGB’ is deprecated [-Wdeprecated-declarations]
  388 |             tonemapping_mode = PL_TONE_MAP_RGB;
      |             ^~~~~~~~~~~~~~~~
In file included from /usr/local/include/libplacebo/renderer.h:25,
                 from libavfilter/vf_libplacebo.c:25:
/usr/local/include/libplacebo/shaders/colorspace.h:219:5: note: declared here
  219 |     PL_TONE_MAP_RGB     PL_DEPRECATED_ENUMERATOR,
      |     ^~~~~~~~~~~~~~~
libavfilter/vf_libplacebo.c:390:13: warning: ‘PL_TONE_MAP_HYBRID’ is deprecated [-Wdeprecated-declarations]
  390 |             tonemapping_mode = PL_TONE_MAP_HYBRID;
      |             ^~~~~~~~~~~~~~~~
In file included from /usr/local/include/libplacebo/renderer.h:25,
                 from libavfilter/vf_libplacebo.c:25:
/usr/local/include/libplacebo/shaders/colorspace.h:221:5: note: declared here
  221 |     PL_TONE_MAP_HYBRID  PL_DEPRECATED_ENUMERATOR,
      |     ^~~~~~~~~~~~~~~~~~
libavfilter/vf_libplacebo.c:392:13: warning: ‘PL_TONE_MAP_LUMA’ is deprecated [-Wdeprecated-declarations]
  392 |             tonemapping_mode = PL_TONE_MAP_LUMA;
      |             ^~~~~~~~~~~~~~~~
In file included from /usr/local/include/libplacebo/renderer.h:25,
                 from libavfilter/vf_libplacebo.c:25:
/usr/local/include/libplacebo/shaders/colorspace.h:222:5: note: declared here
  222 |     PL_TONE_MAP_LUMA    PL_DEPRECATED_ENUMERATOR,
      |     ^~~~~~~~~~~~~~~~
libavfilter/vf_libplacebo.c:397:9: warning: ‘PL_GAMUT_WARN’ is deprecated [-Wdeprecated-declarations]
  397 |         gamut_mode = PL_GAMUT_WARN;
      |         ^~~~~~~~~~
In file included from /usr/local/include/libplacebo/renderer.h:25,
                 from libavfilter/vf_libplacebo.c:25:
/usr/local/include/libplacebo/shaders/colorspace.h:229:5: note: declared here
  229 |     PL_GAMUT_WARN       PL_DEPRECATED_ENUMERATOR, // pl_gamut_map_highlight
      |     ^~~~~~~~~~~~~
libavfilter/vf_libplacebo.c:399:9: warning: ‘PL_GAMUT_DESATURATE’ is deprecated [-Wdeprecated-declarations]
  399 |         gamut_mode = PL_GAMUT_DESATURATE;
      |         ^~~~~~~~~~
In file included from /usr/local/include/libplacebo/renderer.h:25,
                 from libavfilter/vf_libplacebo.c:25:
/usr/local/include/libplacebo/shaders/colorspace.h:231:5: note: declared here
  231 |     PL_GAMUT_DESATURATE PL_DEPRECATED_ENUMERATOR, // pl_gamut_map_desaturate
      |     ^~~~~~~~~~~~~~~~~~~
libavfilter/vf_libplacebo.c:461:10: error: ‘struct pl_render_params’ has no member named ‘force_icc_lut’
  461 |         .force_icc_lut = s->force_icc_lut,

**Comment by zshnb** [comment]
@haasn i try again with ffmpeg master branch with libplacebo 6.292.1, and use this command: `./ffmpeg -y -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 3 -i UPL_0UOVszENQF.mp4 -vf "hwupload=derive_device=vulkan,libplacebo=format=yuv420p10le:colorspace=bt709:color_primaries=bt709:color_trc=bt709,hwdownload,format=yuv420p" -c:v h264_nvenc -c:a copy UPL_0UOVszENQF.libplacebo.cuda.mp4`, here is the output log
[log.log](https://github.com/haasn/libplacebo/files/12300502/log.log)

**Comment by zshnb** [comment]
> ```
> ./ffmpeg -y -init_hw_device vulkan=vk,disable_multiplane=1 -filter_hw_device vk -hwaccel nvdec -hwaccel_output_format cuda -extra_hw_frames 3 -i UPL_0UOVszENQF.mp4 -vf "hwupload=derive_device=vulkan,libplacebo=format=yuv420p10le:colorspace=bt709:color_primaries=bt709:color_trc=bt709,hwupload=derive_device=cuda" -c:v h264_nvenc -c:a copy UPL_0UOVszENQF.libplacebo.cuda.mp4
> ```
> 
> ```
> ./ffmpeg -y -init_hw_device cuda=cu -init_hw_device vulkan=vk@cu -filter_hw_device vk -hwaccel nvdec -hwaccel_output_format cuda -extra_hw_frames 3 -i UPL_0UOVszENQF.mp4 -vf "hwupload=derive_device=vulkan,libplacebo=format=yuv420p10le:colorspace=bt709:color_primaries=bt709:color_trc=bt709,hwupload=derive_device=cuda" -c:v h264_nvenc -c:a copy UPL_0UOVszENQF.libplacebo.cuda.mp4
> ```

first command is this error
```
[h264_nvenc @ 0x55b770cbbac0] 10 bit encode not supported
[h264_nvenc @ 0x55b770cbbac0] Provided device doesn't support required NVENC features
[vost#0:0/h264_nvenc @ 0x55b770c6a300] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
Error while filtering: Function not implemented
[out#0/mp4 @ 0x55b770cbc4c0] Nothing was written into output file, because at least one of its streams received no packets
```
second command is same error

**Comment by zshnb** [comment]
@arm64-v9a i changed libplacebo's format to yuv420p, then it works! i guess nvenc can't use 10bit's frame as input

**Comment by haasn** [comment]
So I guess the original issue is resolved?
