### ISSUE TITLE
vf_libplacebo cannot be linked in mpv

### ISSUE THREAD

**Issue by hooke007** [haasn/libplacebo#188]
I had checked the recent commits on shinchiro's toolchain and mpv. Still have no idea.
check more details on https://github.com/mpv-player/mpv/issues/11993

**Comment by haasn** [comment]
No clue. It gets listed on my end. Maybe check the equivalent of `ldd mpv` to see which versions of libraries it's linking?

**Comment by kasper93** [comment]
Everything is linked correctly, mpv just doesn't support vf_libplacebo, see related issue https://github.com/mpv-player/mpv/issues/11993

**Comment by hooke007** [comment]
No, mpv support. the post you pasted is also mentioned by me.

**Comment by kasper93** [comment]
> No, mpv support. the post you pasted is also mentioned by me.

But we don't need two issues, and this is clearly mpv issue, not libplacebo.

**Comment by hooke007** [comment]
Not sure. That file is touched months ago. But the issue happens recently.

**Comment by kasper93** [comment]
> Not sure. That file is touched months ago. But the issue happens recently.

But I am sure.

> If known which version of mpv introduced the problem https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230624

https://github.com/FFmpeg/FFmpeg/commit/f998a618bac1f61586a3625620e0794c1abba04c 
> haasn committed Jun 20, 2023 committed Jun 20, 2023

**Comment by hooke007** [comment]
Yeah I see it. I commented as you hadn’t edited your comments :-)
