### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [haasn/libplacebo#190]
Is it possible next time on release new version make the github release to have entry on https://github.com/haasn/libplacebo/releases entries? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by haasn** [comment]
I suppose I could make one retroactively now?

**Comment by kloczek** [comment]
yes you can 😄
