### ISSUE TITLE
purple screen when playing dolby vision video on mac using vo=gpu-next

### ISSUE THREAD

**Issue by eko5624** [haasn/libplacebo#195]
Like this:
<img width="1440" alt="2x" src="https://github.com/haasn/libplacebo/assets/84926938/e9767704-e4ec-417f-8c2c-03d5f624b5f2">
log file:
[mpv.log](https://github.com/haasn/libplacebo/files/12505287/mpv.log)
My mac: macbook pro 2017

**Comment by haasn** [comment]
```
[   2.085][e][vo/gpu-next/libplacebo] shader compile log (status=0): ERROR: 0:35: No matching function for call to textureLod(sampler2DRect, vec2, float)
```

Oh no.. this is awful. Truly awful. I was so happy to remove the need to have the sampling function depend on the sampler, only to have to reintroduce it.. ugh. Possible work arounds:

1. `#define textureLod(s,p,b) texture(s,p)` on relevant GLSL
2. Add `${sampler:w/e}` to GLSL preprocessor to insert `texture`/`textureLod` appropriately?

Dunno...

**Comment by eko5624** [comment]
> ```
> [   2.085][e][vo/gpu-next/libplacebo] shader compile log (status=0): ERROR: 0:35: No matching function for call to textureLod(sampler2DRect, vec2, float)
> ```
> 
> Oh no.. this is awful. Truly awful. I was so happy to remove the need to have the sampling function depend on the sampler, only to have to reintroduce it.. ugh. Possible work arounds:
> 
> 1. `#define textureLod(s,p,b) texture(s,p)` on relevant GLSL
> 2. Add `${sampler:w/e}` to GLSL preprocessor to insert `texture`/`textureLod` appropriately?
> 
> Dunno...

Can you make a patch for me, thanks. I need `vo=gpu-next` working on my mac.

**Comment by haasn** [comment]
https://code.videolan.org/videolan/libplacebo/-/merge_requests/564

Can you test if it works?

**Comment by eko5624** [comment]
Thanks, it works!
