### ISSUE TITLE
Adjust Cubic Hermite's BC parameters to the correct values.

### ISSUE THREAD

**Issue by Isaacx123** [haasn/libplacebo#201]
[Currently](https://github.com/haasn/libplacebo/blob/a9f84483a164c4090149ee610d35be0746808888/src/filters.c#L483), Hermite BC values are `B=0.5, C=0.5` when both should be `B=0, C=0`.

[Link to filter function. ](https://github.com/haasn/libplacebo/blob/a9f84483a164c4090149ee610d35be0746808888/src/filters.c#L478C2-L478C2)

Reference:
[Imagemagick Cubic B,C Expert Controls](https://www.imagemagick.org/Usage/filter/#cubic_bc)

**Comment by wiwaz** [comment]
In addition to the b/c values, the filter radius is 2.0, but Hermite only has a single positive lobe.

**Comment by Isaacx123** [comment]
The filter has a [merge request](https://code.videolan.org/videolan/libplacebo/-/merge_requests/587/diffs?commit_id=ca6bf81f50ee366450d1fd420e02b9f42fdaa852), closing the issue now.
