### ISSUE TITLE
scale-antiring creates artifacts when used with a non-ringing kernel

### ISSUE THREAD

**Issue by wiwaz** [haasn/libplacebo#209]
Example: [https://slow.pics/c/nWNIdmHr](https://slow.pics/c/nWNIdmHr)

Instead of being a no-op scale-antiring combined with a non-ringing kernel (I tested hermite and gaussian, both are affected) results in artifacts such as this. This comes up more often than it should because of the already known behavior of scale-antiring applying to cscale and dscale aswell, potentionally creating artifacts when downscaling even if the user only intends to use scale-antiring for upscaling.

**Comment by haasn** [comment]
How to reproduce these artifacts? Settings? Errors? Log?
