### ISSUE TITLE
shaders/sampling: ewa_lanczos4sharpest error (downscaling)

### ISSUE THREAD

**Issue by Asd-g** [haasn/libplacebo#217]
Removing [this constant](https://github.com/haasn/libplacebo/commit/b7da55239ea2f807e56bba469397aa3b566efc20#diff-777976a3fdadb4a87d0bc21189897bd5b1afbd471160d72b1b40ac48e76f1289L702) is causing error [here](https://github.com/haasn/libplacebo/blob/master/src/glsl/spirv_shaderc.c#L74) when resizing for example, 1920x1080->960x516 with an ewa filter.

**Comment by haasn** [comment]
What error? Can you provide more information?

**Comment by Asd-g** [comment]
I attached a log with the error generated with `ffmpeg_g.exe -i ..\21.mkv -vframes 200 -vf "libplacebo=w=960:h=516:extra_opts='downscaler=ewa_lanczos4sharpest'" -f null - > log.txt 2>&1` (ffmpeg built with libplacebo v6.338.1).

I tested ffmpeg with the specific libplacebo version (with or  without [the mentioned constant](https://github.com/haasn/libplacebo/commit/b7da55239ea2f807e56bba469397aa3b566efc20#diff-777976a3fdadb4a87d0bc21189897bd5b1afbd471160d72b1b40ac48e76f1289L702)) and `ewa_lanczos4sharpest` is the only filter from the EWA sinc family that generates these errors.

[The libplacebo implementation I have ](https://github.com/Asd-g/avslibplacebo/blob/main/src/resample.cpp) fails the same way for every EWA sinc family not just `ewa_lanczos4sharpest`. When I use libplacebo built with added the already mentioned constant, the filters (for example, `ewa_lanczos`) works again except `ewa_lanczos4sharpest`.

[log.txt](https://github.com/haasn/libplacebo/files/13248841/log.txt)

**Comment by haasn** [comment]
> -vf "libplacebo=w=960:h=516:extra_opts='downscaler=ewa_lanczos4sharpest'" -f null -

Okay, I can reproduce it, thanks. Will investigate

**Comment by haasn** [comment]
Okay, so there are two bugs:

1. Generation of massive amounts of unused shader constants via the anti-ringing code
2. Somehow this causes namespace conflict which should in theory be impossible

1. is an easy fix, but I need to figure out why this even triggered an error (2)

**Comment by haasn** [comment]
Fixed in https://code.videolan.org/videolan/libplacebo/-/merge_requests/620

**Comment by Asd-g** [comment]
It's ok now. Thanks.
