### ISSUE TITLE
Add external image interop API

### ISSUE THREAD

**Issue by haasn** [haasn/libplacebo#22]
If a user has their own VkImage created from the same VkDevice (e.g. via hwdec interop), there's currently no public way to get that wrapped into a `ra_tex` for consumption by libplacebo. This obviously needs to be remedied.

The appropriate function more or less already exists internally (`ra_vk_wrap_swapchain_image` -> `vk_init_image`). A similar function needs to be created for wrapping generic VkImages, perhaps even replacing the one specialized for swapchains, made public, and documented.

Some thought and research needs to be done in order to figure out the best API for this.

**Comment by haasn** [comment]
This probably also implies refactoring VkDevice creation slightly in order to allow users to create their own VkDevices instead of using ours, or perhaps to enable their own features on top of what we enable.

**Comment by eintw1ck** [comment]
Why can `struct pl_tex *pl_vk_wrap_swimg(const struct pl_gpu *, VkImage, VkSwapchainCreateInfoKHR)` 'not wrap generic images'?

**Comment by haasn** [comment]
It can, is what I'm trying to say. But there might be some headache related to synchronization that we have to figure out. The exact API and semantics needs to be made clear and documented.

I mean, the whole point of using a shared VkImage is that the caller is also able to do something with that VkImage - but the problem here is that there's no way to do anything with a VkImage once you've passed it to that function. The only reason it works for swapchains is because the `pl_vk_finish_frame` takes care of it. But this is hard-coded for the needs of swapchain images. It needs to be generalized.
