### ISSUE TITLE
Time as a parameter in a custom shader

### ISSUE THREAD

**Issue by AaronPorts** [haasn/libplacebo#230]
Is it possible to somehow use the current file playback time in custom shaders?

**Comment by haasn** [comment]
From the PoV of the libplacebo API, there's nothing stopping you from doing this. It would be a matter of convention on the side of the API user (e.g. mpv).

It would be very easy to add this to mpv, would you mind opening an issue there?

**Comment by haasn** [comment]
Okay. I cooked up something there.
