### ISSUE TITLE
Sinc filter does not work with videos

### ISSUE THREAD

**Issue by lextra2** [haasn/libplacebo#248]
Command used to test:
`ffmpeg -y -benchmark -init_hw_device vulkan -i "input" -vf "libplacebo=w=iw*2:h=ih*2:upscaler=sinc" -c:v libx264 -preset ultrafast -qp 0 -g 1 -an test123.mkv
`

Some comparisons:

Spline36 (Avisynth)
![spline36](https://github.com/haasn/libplacebo/assets/20690384/a81b8bb2-892b-4e3f-a640-1e65e3bdb0be)

Sinc (Avisynth) How it is supposed to look
![sinc](https://github.com/haasn/libplacebo/assets/20690384/d282e79e-2df8-426c-a2db-74fc8a77b9ed)

Bilinear (Avisynth)
![bilinear](https://github.com/haasn/libplacebo/assets/20690384/e592dd3d-44d9-4747-959f-1abf8ae766cc)

Sinc (libplacebo) Looks blurrier then Bilinear
![placebo_sinc](https://github.com/haasn/libplacebo/assets/20690384/7d731620-2290-4668-9eb1-8c9ad7099066)

The same thing happens with gpu-next in MPV:  https://github.com/mpv-player/mpv/issues/13672

**Comment by Chipcraft** [comment]
Can you provide the same source frame you used, as a reference?

Avisynth is using four taps for Sinc, whereas libplacebo uses three taps however, that is unlikely to cause the difference.
Within libplacebo itself, Sinc is clearly superior to bilinear.

**Comment by lextra2** [comment]
> Can you provide the same source frame you used, as a reference?
> 

![mpv-shot0001](https://github.com/haasn/libplacebo/assets/20690384/3cc2ca8e-7c87-44b7-978d-e7531ea335e3)

> Within libplacebo itself, Sinc is clearly superior to bilinear.
>
I've only included bilinear for sharpness comparison

**Comment by Chipcraft** [comment]
Cannot replicate the output with libplacebo e987124b and [ffmpeg master ab2173c0a5](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/ab2173c0a5).

`ffmpeg -init_hw_device vulkan -i 313426824-3cc2ca8e-7c87-44b7-978d-e7531ea335e3.png -vf libplacebo=upscaler=sinc:w=iw*2:h=ih*2 -pix_fmt rgb24 Sinc_Out.png`

[https://nle-chipcraft.com/Git/Sinc_Out.png](https://nle-chipcraft.com/Git/Sinc_Out.png)

**Comment by lextra2** [comment]
> Cannot replicate the output with libplacebo [e987124](https://github.com/haasn/libplacebo/commit/e987124b516507f4eb71a29b53e288d3c590aa75) and [ffmpeg master ab2173c0a5](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/ab2173c0a5).
> 
> `ffmpeg -init_hw_device vulkan -i 313426824-3cc2ca8e-7c87-44b7-978d-e7531ea335e3.png -vf libplacebo=upscaler=sinc:w=iw*2:h=ih*2 -pix_fmt rgb24 Sinc_Out.png`
> 
> https://nle-chipcraft.com/Git/Sinc_Out.png

Yeah weird. That works.
And
`ffmpeg -loop 1 -init_hw_device vulkan -i input.png -c:v libx264 -qp 0 -t 15 -vf libplacebo=upscaler=sinc:w=iw*2:h=ih*2 -pix_fmt yuv420p test.mp4`

works too.
But this code
`ffmpeg -init_hw_device vulkan -i input.mkv -vf "libplacebo=w=iw*2:h=ih*2:upscaler=sinc" -c:v libx264 -preset ultrafast -qp 0 -an test567.mkv`
does not work.

**Comment by lextra2** [comment]
Here, [try this 30 seconds snippet.](https://mega.nz/file/wsQkwbYS#kuj48cLCrHyqWQ_fzz-Xo3PZyxOToy1ze8dJMJUgp00)
Reference frame is at 0:25.025 (Frame 600)

**Comment by lextra2** [comment]
fixed in https://github.com/haasn/libplacebo/commit/76bb971847a5c7f5a40596edcb071de5ab8b7446
