### ISSUE TITLE
Query on: HDR passthrough in ffmpeg's libplacebo's filter 

### ISSUE THREAD

**Issue by Brainiarc7** [haasn/libplacebo#251]
Hello there,

Does `ffmpeg`'s `libplacebo` filter implementation support HDR passthrough?
Is there a switch needed to enable this, or is this toggled on by default?
I see an [MR](https://code.videolan.org/videolan/vlc/-/merge_requests/906) on this topic opened ~2 years ago, with the description:

```sh
Technically, this just requires forwarding the colorspace and HDR
metadata information to the libplacebo swapchain.
In practice, this does nothing at all on OpenGL, and for Vulkan it only
works with implementations that provide VK_KHR_swapchain_colorspace and
VK_EXT_hdr_metadata, which in practice means "Windows, Wayland and DRM
only", although we don't support DRM or wayland (yet) so it really just
means "Windows only".
```

Does the same also apply to the filter?

**Comment by haasn** [comment]
https://ffmpeg.org/ffmpeg-filters.html#Output-mode

> Configure the colorspace that output frames will be delivered in. The default value of `auto` outputs frames in the same format as the input frames, leading to no change. For any other value, conversion will be performed.

The MR you quoted has nothing to do with the filter, it's talking about output to the display.
