### ISSUE TITLE
How can I draw rectangle on pl_vulkan?

### ISSUE THREAD

**Issue by jskimn** [haasn/libplacebo#277]
Dear,
I could not find a good example that can draw rectangle on pl_vulkan.
If somebody knows how can I learn about that, please help me.
I want to draw rectangle or text on ffplayer, and it is rendering the video frame via vulkan render using libplacebo.

**Comment by haasn** [comment]
Hi,

You may want to look into what `plplay` does: https://github.com/haasn/libplacebo/blob/master/demos/ui.c#L146

Basically, prepare a font/glyph atlas or pre-render the text, upload it to a texture, then blit that to the places you want using `pl_dispatch_vertex` + `pl_shader_custom`. (You could also use this to blit a solid color rectangle)

**Comment by jskimn** [comment]
> Hi,
> 
> You may want to look into what `plplay` does: https://github.com/haasn/libplacebo/blob/master/demos/ui.c#L146
> 
> Basically, prepare a font/glyph atlas or pre-render the text, upload it to a texture, then blit that to the places you want using `pl_dispatch_vertex` + `pl_shader_custom`. (You could also use this to blit a solid color rectangle)

Dear,
Thanks for your comment. I will try to do it.
