### ISSUE TITLE
macOS: Building 7.349.0 requires vulkan headers and jinja2 even when vulkan features are explicitly disabled

### ISSUE THREAD

**Issue by i0ntempest** [haasn/libplacebo#289]
In the log you may see that vulkan features are disabled yet it still tries to use vulkan headers.
[main.log](https://github.com/user-attachments/files/17124149/main.log)

**Comment by haasn** [comment]
Hi,

This is by design - we still need those headers to be able to provide the fallback API stubs when vulkan is disabled. This is only a build-time dependency. If you do a deep clone of the git repository, suitable headers should have been included automatically.
