### ISSUE TITLE
Feature Request: allow seperate control over upward and downward auto exposure correction (HDR-tonemapping)

### ISSUE THREAD

**Issue by geextahslex** [haasn/libplacebo#305]
Hi, at the moment you can either enable or disable this "auto exposure correction" my suggestion is to have more control over it.
As for now the upward correction of the image (brightening) has some issues with saturation (also too bright night scenes which look unnatural) but the downward correction works fine. It would be great if you could have the downward (darkening of the image) exposure correction without dealing with the upward (brightening) issues.

It could be on/off or percantage 0-100%

`hdr-upward-correction=0-100%`
`hdr-downward-correction=0-100%`

sidenote: I'm not sure if this belongs more to libplacebo or mpv

Thank you :)

**Comment by haasn** [comment]
I'm not sure what exactly you mean. What "auto exposure correction" are you disabling?

As for darkening vs brightening the image, we fundamentally *have* to brighten the image to display it on a monitor with a limited contrast. I'm not sure what exactly you expect us to do instead.

**Comment by geextahslex** [comment]
I mean leave it like this
![dark](https://github.com/user-attachments/assets/b1cf430c-792d-4927-9f64-22eb0e222b8f)

and don't brighten it like this
![bright](https://github.com/user-attachments/assets/d0360ec1-8a52-4de1-9b2c-bb59f1f7e2e8)

I don't know which system does this change but it gets applied only when I move my mouse
