### ISSUE TITLE
hdr tonemapping: crushed blacks/artifacting with default trc=pq

### ISSUE THREAD

**Issue by geextahslex** [haasn/libplacebo#306]
Hi, I have noticed crushed blacks/artifacting in dark areas. So you loose detail and get some nasty color banding. This gets solved when you raise the brightness by 2-4 or switch `target-trc` from the default `pq` to `srgb` or `bt.1886` but this messes up dark scenes contrast and saturation.
I'm not sure what to do at this point. You either get one (consistent contrast, saturation but crushed blacks) or the other (fine blacks but messed up saturation and contrast)

You have to watch these screenshots at fullscreen because here in the preview they all look broken/have banding

Thank you :)

sample to the first scene
[Vikings.Valhalla.zip](https://github.com/user-attachments/files/17936220/Vikings.Valhalla.mkv.zip)

corners and her dress, hair
![crushed blacks artifacts](https://github.com/user-attachments/assets/586dc938-e883-4a85-a203-f3197e7560ef)
![crushed blacks artifacts bright2](https://github.com/user-attachments/assets/0511596c-ebc0-4798-a229-1636ca4c1114)

in the middle of the arrow where it goes from shadow to highlight
![shadows bending](https://github.com/user-attachments/assets/f8245772-b088-49cb-bf25-d33c4953ddd4)
![shadows bending brightness plus2](https://github.com/user-attachments/assets/d591dd26-824c-439c-9d81-5d7dc39cc81d)

marked with yellow, crushed red color
![artifacts](https://github.com/user-attachments/assets/0f212563-cb8b-45c6-bcdf-06b1131b10ab)
![artifacts no](https://github.com/user-attachments/assets/9491c3a8-69b5-4a57-8c8a-0eb93847da64)

**Comment by kasper93** [comment]
`target-trc=pq` is practice is only valid if you are doing HDR passthrough. PQ is scaled to 0, so if your display cannot handle it it will crash blacks. The other is tone-mapping and bt.1886 is setting 1000:1 contrast ratio by default, so the blacks are raised.

There is too little information, what your are trying to do, what hardware do you have and son on.

Default (mpv) config is best starting point.

**Comment by geextahslex** [comment]
I want HDR content (movies, series) tonmapped to SDR. I have a SDR TV. 
```
vo=gpu-next
target-peak=80
hdr-compute-peak=yes
allow-delayed-peak-detect
```
logfile
[output.txt](https://github.com/user-attachments/files/17938584/output.txt)

Content
![content](https://github.com/user-attachments/assets/37b6b9e0-058b-4e36-8708-8b5e139ffbd4)

What else information is needed?

**Comment by geextahslex** [comment]
Im using this version
### mpv Information

```bash
mpv v0.39.0-355-g45c1c586 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov 19 2024 00:07:00
libplacebo version: v7.349.0 (v7.349.0-26-g5788a82-dirty)
FFmpeg version: N-117832-ge9c3698ed
FFmpeg library versions:
   libavcodec      61.25.100
   libavdevice     61.4.100
   libavfilter     10.6.101
   libavformat     61.9.100
   libavutil       59.47.100
   libswresample   5.4.100
   libswscale      8.9.101
```
I can grab [this version from 19 hours ago](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20241127) if you think this helps

okay `target-colorspace-hint=no` changed nothing with `trc=srgb` and with `trc=pq` this washes out the scene so it looks almost exactly like with `trc=srgb`

**Comment by kasper93** [comment]
> I can grab [this version from 19 hours ago (shinchiro)](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20241127) if you think this helps

Yes, this helps. `target-colorspace-hint` were fixed 4 days ago https://github.com/mpv-player/mpv/pull/15279

> okay target-colorspace-hint=no changed nothing with trc=srgb

Expected.

> with trc=pq this washes out the scene

Expected. You don't want PQ output on non-hdr display.


Just to explain, `target-colorspace-hint=yes` which is default, on the build you are using. HDR is passhrough to compositor, which is tone-mapping it to SDR. Windows tonemapping is pretty basic, it is basically clipping, so shouldn't be used.

```
vo=gpu-next
target-peak=80
hdr-compute-peak=yes
allow-delayed-peak-detect
target-colorspace-hint=no
```

With this settings, mpv will use proper tone-mapping to SDR. Problem in practice is that libplacebo, doesn't work very well in low-nits scenarios, `target-peak=80` is quite low and may have problems. This is known issue. libplacebo is optimized for default tone-mapping to 203 nits.

**Comment by geextahslex** [comment]
Okay so nothing have changed, the cave scene still looks washed out
![srgb broken dark scene](https://github.com/user-attachments/assets/2f3eab95-07f2-4553-aff9-dfb99becf851)

with 200nits it looks the same washed out but slightly darker, so its not about that
![200nits](https://github.com/user-attachments/assets/64eb7c7e-c53c-47b7-b9cd-c3cea95ea4f5)

it should look like this
![like this](https://github.com/user-attachments/assets/40161931-0afc-4081-867a-c1663296fd7e)

**Comment by kasper93** [comment]
> it should look like this

Not really. People are not deep red on their faces.

**Comment by kasper93** [comment]
> target peak 80 washed out

This is really dark still. It shouldn't be this dark, especially with target-peak 80. Do you have other things in config? Is this DV file? Try with `vf=format=dolbyvision=no`.

**Comment by geextahslex** [comment]
No in these files there is no DV they are HDR10 both.
I don't understand why `target-peak` is changing the saturation in `trc=srgb`, with `trc=pq` the saturation stays constant and `target-peak` only affects the brightness. You would have to decouple them (`target-peak` from saturation in `trc=srgb`).

**Comment by geextahslex** [comment]
Also to include an external source to these comparisons here you have [hdr-toys](https://github.com/natural-harmonia-gropius/hdr-toys) with mpv
and there is color in these scenes
![harmonia](https://github.com/user-attachments/assets/fc527ca4-d5ee-47d4-b738-87114dded004)
![harmonia1](https://github.com/user-attachments/assets/33e85d5d-629b-4cb9-8a64-6707e50242b0)
![harmonia2](https://github.com/user-attachments/assets/c3370d4c-e358-4577-bbb7-1abc5efee326)

**Comment by kasper93** [comment]
You can experiment with `gamut-mapping-mode`, if you like any of them better.

**Comment by geextahslex** [comment]
I tested all 9 and none of them solves this issue, the only thing that helps is `vf=format=sig-peak=4.926` (constant 1000 nits)  loosing the ability of any dynamic adjustment. Or setting `target-trc=pq` and having crushed blacks.

**Comment by geextahslex** [comment]
So after further testing I ended up using [hdr-toys](https://github.com/natural-harmonia-gropius/hdr-toys) for all of the "color space" stuff (gamut-mapping and transfer function) and mpv only does the tone-mapping with 2094-10. 

On a SDR TV this gives you the best result
```
target-prim=bt.2020
target-trc=pq
tone-mapping=st2094-10
gamut-mapping-mode=clip (clip because hdr-toys handles this)
target-peak=100
hdr-compute-peak=yes
allow-delayed-peak-detect

glsl-shader=~~/shaders/hdr-toys/transfer-function/pq_inv.glsl
glsl-shader=~~/shaders/hdr-toys/utils/black_point_compensation.glsl
glsl-shader=~~/shaders/hdr-toys/gamut-mapping/jedypod.glsl
glsl-shader=~~/shaders/hdr-toys/transfer-function/bt1886.glsl
glsl-shader-opts=L_hdr=1000,L_sdr=100
```
![1 dd](https://github.com/user-attachments/assets/d3fc6ed0-b60a-4276-8e38-2e2e1f15c412)
![2 dd](https://github.com/user-attachments/assets/02f3d671-957c-4bdd-accd-10853a6c5400)
