### ISSUE TITLE
bstr.c needs <limits.h> to build with Android gnustl

### ISSUE THREAD

**Issue by sk2212** [haasn/libplacebo#34]
I get following error when trying to compile VLC 3.0.x using stl "gnustl" with Android NDK r14b with ABI 9:

/media/data1/libvlc_trunk/toolchains/arm/bin/clang  -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -DNDEBUG  -I/media/data1/libvlc_trunk/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_ISOC99_SOURCE -D_GNU_SOURCE -Isrc -Isrc/osdep -Isrc/include -fvisibility=hidden -Wall -Wundef -Wmissing-prototypes -Wshadow -Wparentheses -Wpointer-arith -Wno-pointer-sign  -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -DNDEBUG  -I/media/data1/libvlc_trunk/vlc/contrib/arm-linux-androideabi/include -fPIC  -c -o src/bstr/bstr.o src/bstr/bstr.c
src/bstr/bstr.c:277:21: error: use of undeclared identifier 'SIZE_MAX'
        if (size >= SIZE_MAX / 2 || append_min >= SIZE_MAX / 2)
                    ^
src/bstr/bstr.c:277:51: error: use of undeclared identifier 'SIZE_MAX'
        if (size >= SIZE_MAX / 2 || append_min >= SIZE_MAX / 2)
                                                  ^
2 errors generated.
make[1]: *** [src/bstr/bstr.o] Error 1
make[1]: Leaving directory `/media/data1/libvlc_trunk/vlc/contrib/contrib-android-arm-linux-androideabi/libplacebo'
make: *** [.libplacebo] Error 2

Adding '#include <limits.h>' does fix the error.

Is there any other solution?

**Comment by haasn** [comment]
Don't think so, but I don't think throwing an `#include <limits.h>` in there will affect any other platform negatively, so I'd be happy to accept a 1-line patch that adds this. Do you want to submit one?
