### ISSUE TITLE
Unconditional use of VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT

### ISSUE THREAD

**Issue by ePirat** [haasn/libplacebo#39]
The `VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT` is not available in some older Vulkan versions, as per discussion on IRC, it should be `#ifdef`ed.

```
../src/vulkan/swapchain.c:80:10: error: use of undeclared identifier 'VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT'; did you mean 'VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT'?
    case VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT:
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by haasn** [comment]
I can add the #ifdef, but I'm a bit confused: How come that specific identifier is missing for you, but the other ones aren't? They're all defined by the same exception (`VK_EXT_swapchain_colorspace`).
