### ISSUE TITLE
cannot build libplacebo

### ISSUE THREAD

**Issue by 3PO** [haasn/libplacebo#50]
Hi, 
i cannot build libplacebo.

    vdr01_64 tmp # git clone https://github.com/haasn/libplacebo
    Klone nach 'libplacebo' ...
    remote: Enumerating objects: 130, done.
    remote: Counting objects: 100% (130/130), done.
    remote: Compressing objects: 100% (64/64), done.
    remote: Total 3895 (delta 71), reused 99 (delta 59), pack-reused 3765
    Empfange Objekte: 100% (3895/3895), 1.22 MiB | 2.67 MiB/s, Fertig.
    Löse Unterschiede auf: 100% (2800/2800), Fertig.
    vdr01_64 tmp # cd libplacebo
    vdr01_64 libplacebo # DIR=./build
    vdr01_64 libplacebo # meson $DIR
    The Meson build system
    Version: 0.48.1
    Source dir: /tmp/libplacebo
    Build dir: /tmp/libplacebo/build
    Build type: native build
    Project name: libplacebo
    Project version: undefined
    Native C compiler: ccache cc (gcc 7.3.0 "gcc (Gentoo 7.3.0-r3 p1.4) 7.3.0")
    Native C++ compiler: ccache c++ (gcc 7.3.0 "c++ (Gentoo 7.3.0-r3 p1.4) 7.3.0")
    Build machine cpu family: x86_64
    Build machine cpu: x86_64
    Compiler for C supports arguments -Wincompatible-pointer-types: YES
    Compiler for C supports link arguments -Wl,--exclude-libs=ALL: YES
    Dependency threads found: YES
    Library m found: YES
    Found pkg-config: /usr/bin/pkg-config (0.29.2)
    Dependency vulkan found: YES 1.1.82
    Library glslang found: YES
    Library HLSL found: YES
    Library OGLCompiler found: YES
    Library OSDependent found: YES
    Library SPIRV found: YES
    Library SPVRemapper found: YES
    Fetching value of define "GLSLANG_PATCH_LEVEL": 2888
    Dependency lcms2 found: YES 2.9
    Library shaderc_shared found: YES
    Program git found: YES (/usr/bin/git)
    Configuring config.h using configuration
    Build targets in project: 1
    Found ninja-1.8.2 at /usr/bin/ninja
    vdr01_64 libplacebo # LC_MESSAGES=C ninja -C$DIR
    ninja: Entering directory `./build'
    [32/33] Compiling C object 'src/src@@placebo@sha/spirv_shaderc.c.o'.
    FAILED: src/src@@placebo@sha/spirv_shaderc.c.o
    ccache cc -Isrc/src@@placebo@sha -Isrc -I../src -I../src/./include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -g -Wall -Wundef -Wshadow -Wparentheses -Wpointer-arith -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -D_ISOC99_SOURCE -D_GNU_SOURCE -D_XOPEN_SOURCE=700 -U__STRICT_ANSI__ -fvisibility=hidden -Wmissing-prototypes -Wno-pointer-sign -fPIC -pthread  -MD -MQ 'src/src@@placebo@sha/spirv_shaderc.c.o' -MF 'src/src@@placebo@sha/spirv_shaderc.c.o.d' -o 'src/src@@placebo@sha/spirv_shaderc.c.o' -c ../src/spirv_shaderc.c
    ../src/spirv_shaderc.c: In function ‘shaderc_init’:
    ../src/spirv_shaderc.c:49:13: error: ‘shaderc_optimization_level_performance’ undeclared (first use in this function); did you mean ‘shaderc_optimization_level_zero’?
                 shaderc_optimization_level_performance);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 shaderc_optimization_level_zero
    ../src/spirv_shaderc.c:49:13: note: each undeclared identifier is reported only once for each function it appears in
    ninja: build stopped: subcommand failed.
    vdr01_64 libplacebo #

What do i wrong?

**Comment by haasn** [comment]
You need a newer version of libshaderc.

Unfortunately, google engineering being as stellar as it is, there's no real way for us to check the version of shaderc either at configure time or at compile time. They don't expose any version macros or an ABI version, and they don't have a pkg-config file.

**Comment by 3PO** [comment]
Thanks!
I installed the git version of libshaderc and now it works.
