### ISSUE TITLE
swapchain frames are not cleared

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#54]
When I use a swapchain I get the frames with the old Image on it. That is unfortunate if I render on this frame  only a smaller Image than before e.g. render the frame into a small rectangle to show it in the OSD.  Is there a way to get cleared frames from the swapchain ? 
I know that I can clear the received frame but that is an additional renderstep.

**Comment by haasn** [comment]
No, you must `pl_tex_clear`. Anything we could do internally would amount to the same thing.

If this causes you a serious performance regression, there are some tricks we can try and do to make `pl_tex_clear` cheaper. (Without changing the API)

**Comment by jojo61** [comment]
Thanks that helped me out.  Sometimes I need to read more to find the right funktions :-)
