### ISSUE TITLE
With Intel VA Colorconversion from BT2020 to BT709 crashes

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#63]
Hi
when using an Intel VA Driver and showing a UHD HDR file, then the  Intel driver crashes with:
kernel: [  597.131638] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0

This happens when I convert from BT2020 to BT709 only.  Without the conversion everything works fine. I know this is an Intel issue, but I wonder what shader commands you use that crashes the driver. It will compile without errors.  Maybe libplacebo can use some other commands that will not crash the driver.

**Comment by haasn** [comment]
Do you have some sort of log of the failure case, and ideally a log of a similar case where it doesn't crash?

**Comment by jojo61** [comment]
Her are 2 debug files. The Failure file is with conversion from BT2020 to sRGB and the good file is with conversion from BT709 to sRGB.   Of course the goodf file has the wrong conversion  In both cases   I play the same UHD HDR file.

[failure.txt](https://github.com/haasn/libplacebo/files/3574949/failure.txt)
[good.txt](https://github.com/haasn/libplacebo/files/3574951/good.txt)

**Comment by haasn** [comment]
So I noticed a number of operations that are only present in the failure case:

1. BT.2020 -> BT.709 pimary conversion
2. PQ linearization
3. PQ ootf
4. Tone mapping function
5. HDR peak detection compute shader

Out of all of these, the overwhelmingly most likely candidate for the crash is the peak detection shader. Try disabling it (setting the HDR peak detection period to 0).

**Comment by jojo61** [comment]
Yes the HDR peak detection shader is the culprit. I disabled it and now it works. 
As this is not realy a libplacebo issue I will close it. Maybe you can look into the HDR peak detection shader and find another way to do it. But this is realy a Intel shader problem. 
Thanks for your help.

**Comment by haasn** [comment]
I've run into the same issue and decided to disable compute shaders on Intel for now. I'll see if I can't get it fixed this week, maybe in mesa.
