### ISSUE TITLE
Error message spam with minimized video

### ISSUE THREAD

**Issue by adisib** [haasn/libplacebo#65]
I am running into this issue with mpv using the vulkan setting for gpu-api. It was suggested to me that I should file an issue with libplacebo due to it likely being issue with the library logging excessively.

The issue is that whenever video is minimized while playing, the console is continuously spammed with the following error messages:
`[vo/gpu/vulkan/libplacebo] Failed resizing swapchain: unknown size?
[vo/gpu/vulkan/libplacebo] Failed (re)creating swapchain!`

Playback does not seem to be adversely affected as far as I can tell and the messages stop once the video is un-minimized, but it is annoying.

This is using the latest shinchiro Windows build of mpv, with an rx570 using latest drivers on Windows 10.
Here is the mpv log file if it is useful:
https://pastebin.com/TyP5hGKA

**Comment by haasn** [comment]
Oh, I just saw you're on *windows*, not *wayland*. Never mind my previous comment. I can try reproducing it in the upcoming week, I suppose.

**Comment by haasn** [comment]
Sorry for the delay. Finally got round to looking into this. f2178b8d26ab should probably help, can you test it?

**Comment by adisib** [comment]
I've found some time to look into making a Windows build for mpv, and the cross-compile just now finally finished. I can confirm that the issue is not present; minimizing with vulkan behaves as expected, and I am not receiving any warning/error messages from libplacebo.

Thank you for your great work on this software, and happy holidays!
