### ISSUE TITLE
Redundant pow() in 2020-CL handling

### ISSUE THREAD

**Issue by tdaede** [haasn/libplacebo#7]
Here, RGB is converted to R'G'B':

https://github.com/haasn/libplacebo/blob/master/src/shaders/colorspace.c#L87

However, the function already has Y'B'R' from an earlier step, so only the G' needs to be computed. I am not sure this will be faster in practice, so it needs to be benchmarked.

**Comment by haasn** [comment]
Might as well be time to write a benchmarking framework for libplacebo so we can answer these questions now and in the future.
