### ISSUE TITLE
opengl no export_caps

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#70]
I try to test the opengl Version but wonder if it is already in a useable state.

So far I am blocked because with opengl there are no export_caps available.  Is this missing or is there any other way to interact with textures. I need the export for interfacing with cuvid frames.

**Comment by haasn** [comment]
It's unimplemented. Patches welcome. cc @philipl

**Comment by haasn** [comment]
Migrated to https://code.videolan.org/videolan/libplacebo/-/issues/80
