### ISSUE TITLE
add custom shader support 

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#78]
Hi
could you provide an example code how to use custom shaders ?

jojo61

**Comment by haasn** [comment]
I'm not sure what this is about, exactly. If you want an example of what user shaders should look like, [check the mpv wiki's shaders section](https://github.com/mpv-player/mpv/wiki/User-Scripts#user-shaders).

If you want to see how to integrate user shaders with the libplacebo API, check the [dav1dplay example](https://code.videolan.org/haasn/dav1d/-/commit/9027d4c04c8f853b8460bc6fd1476cd38ff9b158).

It boils down to creating the hook with `pl_mpv_user_shader_parse`, and then attaching it to your `pl_render_params` via the `hooks`/`num_hooks` fields.

**Comment by haasn** [comment]
I've been meaning to rewrite the SDL2 example to have more principled options parsing, then we can add e.g. shaders and the likes to that example as well.

**Comment by jojo61** [comment]
> If you want to see how to integrate user shaders with the libplacebo API, check the [dav1dplay example](https://code.videolan.org/haasn/dav1d/-/commit/9027d4c04c8f853b8460bc6fd1476cd38ff9b158).

Thanks that is exacly what I was looking for.
