### ISSUE TITLE
Question about relationship between color spaces and ICC profiles.

### ISSUE THREAD

**Issue by akvadrako** [haasn/libplacebo#82]
This is just a question, but I don't see a better place to ask it.

I'm a bit unclear about the relationship between `pl_color_space` and `pl_icc_profile` when using `pl_render_image`. My limited understanding is that an ICC profile defines a color space, so they seem redundant.

What should I do with `target.color` if `target.profile` is a wide gamut ICC profile, say a standard Rec2020 profile? I get different results if I set it to `pl_color_space_bt2020_hlg` vs leaving it blank.

**Comment by haasn** [comment]
I think currently the only thing we use `target.color` for when specifying an ICC profile is:

- As a fallback when `lcms` is not available, or the ICC profile fails parsing
- Drawing target overlays (which don't go through the ICC profile codepath at the moment)
- (Rarely) During the application of `pl_render_params.cone_params`

So in theory you shouldn't get different results by specifying a different color space. If you do, I'll consider it a bug.

**Comment by akvadrako** [comment]
I have created a minimal test case to demonstrate my issue: https://github.com/akvadrako/pl_bug

It runs pl_render twice, once with no colorspace and once with, and displays the output side by side.

**Comment by haasn** [comment]
Thank you for the great test case. A trivial bug with a trivial solution.
