### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#87]
With the latest Version I have the following compile failure for all FOURCC definitions:

../src/gpu.c:333:21: error: initializer element is not constant
 #define FOURCC(str) ((uint32_t)(str[0]) | ((uint32_t)(str[1]) << 8) | \
                     ^
../src/gpu.c:343:21: note: in expansion of macro ‘FOURCC’
     {"r8",          FOURCC("R8  ")},
                     ^~~~~~
../src/gpu.c:333:21: note: (near initialization for ‘pl_fmt_fourccs[0].fourcc’)
 #define FOURCC(str) ((uint32_t)(str[0]) | ((uint32_t)(str[1]) << 8) | \
                     ^
../src/gpu.c:343:21: note: in expansion of macro ‘FOURCC’
     {"r8",          FOURCC("R8  ")},
                     ^~~~~~
../src/gpu.c:333:21: error: initializer element is not constant
 #define FOURCC(str) ((uint32_t)(str[0]) | ((uint32_t)(str[1]) << 8) | \
                     ^
../src/gpu.c:345:21: note: in expansion of macro ‘FOURCC’
     {"r16",         FOURCC("R16 ")},
                     ^~~~~~
../src/gpu.c:333:21: note: (near initialization for ‘pl_fmt_fourccs[1].fourcc’)
.....

Also VK_RESULT_EXT_298_RESERVED_VALUE_0_EXT is nowhere to be found,.

**Comment by haasn** [comment]
> Also VK_RESULT_EXT_298_RESERVED_VALUE_0_EXT is nowhere to be found,.

298? Do you mean 289? This extension is already blacklisted in utils_gen.py because it's a pseudo-extension. Open a separate issue with the exact error you're getting (and the vk.xml on your system).
