### ISSUE TITLE
Failure in gl_tex_import

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#88]
Hi 
in the function gl_tex_import in src/opengl/gpu.c   you write 
 ADD_DMABUF_PLANE_ATTRIBS(0, tex_gl->fd, shared_mem->offset, **params->w**);
here params->w is wrong for UV planes.  In UV planes the width is only width/2 but you need the pitch here.
I suggest you extend the struct  pl_shared_mem with an additional value pitch. Then it would look like:
ADD_DMABUF_PLANE_ATTRIBS(0, tex_gl->fd, shared_mem->offset, **shared_mem->pitch**)

I tried it myself and then it works flawless.

mfg
jojo61

**Comment by haasn** [comment]
Good suggestion. Will fix after the holidays are over and I'm back at home, unless somebody wants to submit a PR.
