### ISSUE TITLE
Alpha blending with opengl

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#89]
Hi

in opengl/gpu.c iin function gl_fb_query  you write:
.caps = PL_FMT_CAP_RENDERABLE | PL_FMT_CAP_BLITTABLE, 
but then alpha blending does not work. With
.caps = PL_FMT_CAP_RENDERABLE | PL_FMT_CAP_BLITTABLE | PL_FMT_CAP_BLENDABLE,
it will work. 
I think you should enable blending here for fbo's.

One more thing. I get  info: Found no storable FBO format; compute shaders disabled. When using opengl. Is this realy correct or also a missing caps somewhere ?

**Comment by haasn** [comment]
Good point. Seems like an oversight. I'll fix it.

> One more thing. I get info: Found no storable FBO format; compute shaders disabled. When using opengl. Is this realy correct or also a missing caps somewhere ?

> Is this realy correct or also a missing caps somewhere ?

Post a log for this. (In a separate issue, please)
