### ISSUE TITLE
HDR Peak detection fails

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#91]
HI,

when trying to render a HDR frame I get the following failure:

error: Found no memory type matching property flags 0x3 and type bits 0x681!
debug: Freeing slab of size 1048576
error: Failed creating peak detection SSBO!
 warn: Failed creating HDR peak detection shader.. disabling
error: Attempting to modify a failed shader!

If I disable peak detection everything is fine.

**Comment by haasn** [comment]
Hey. Can you post a full log?

**Comment by jojo61** [comment]
[log.txt](https://github.com/haasn/libplacebo/files/5964333/log.txt)

Search for SSBO to find the right place.
