### ISSUE TITLE
VK_IMAGE_TILING_LINEAR   is not used

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#93]
HI

in order to get a picture with intel I needed to change in src/vulkan/gpu.c:

        VkPhysicalDeviceImageFormatInfo2KHR pinfo = {
            .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2_KHR,
            .pNext = &ext_pinfo,
            .format = VK_FORMAT_R8_UNORM,
            .type = VK_IMAGE_TYPE_2D,
//            .tiling = VK_IMAGE_TILING_OPTIMAL,
            .tiling = VK_IMAGE_TILING_LINEAR,
            .usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT,
        };

I use Mesa 20.3.4

**Comment by haasn** [comment]
Can you provide more context? (log? what are you trying to do?)

**Comment by jojo61** [comment]
You fixed it with commit "vulkan: fix vk_tex_handle_caps "  on Feb 11. 
Then you changed it again with commit   "vulkan: implement support for DRM format modifiers"  on Feb 13.  I think that was a mistake.

**Comment by haasn** [comment]
I'm not sure I understand the issue. The commit in question (support for DRM format modifiers) still uses `VK_IMAGE_TILING_LINEAR` in the fallback code. Specifically, this section:

```c
        if (res != VK_SUCCESS && handle_type == PL_HANDLE_DMA_BUF && !has_drm_mods) {
            // Try again with VK_IMAGE_TILING_LINEAR, as a dumb hack
            pinfo.tiling = VK_IMAGE_TILING_LINEAR;
            res = vk->GetPhysicalDeviceImageFormatProperties2KHR(vk->physd, &pinfo, &props);
        }
```

Does this fallback path not work for you?

**Comment by haasn** [comment]
Actually, from your other issue, it seems like you *do* have DRM modifier support, so it should actually be hitting this line:

```
        if (handle_type == PL_HANDLE_DMA_BUF && has_drm_mods) {
            vk_link_struct(&pinfo, &drm_pinfo);
            pinfo.tiling = VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT;
        }
```

In which case, your suggested change does not actually change anything, because this function overrides it anyway. Can you please clarify how you are testing / post a log?

**Comment by jojo61** [comment]
After changing the DMA parameters as suggested see #92 the problem is gone.
