### ISSUE TITLE
Does it can do sdr to hdr10 tone mapping?

### ISSUE THREAD

**Issue by lancodec** [haasn/libplacebo#96]
sdr in bt.709 gamma 
hdr10 in bt 2020 PQ

**Comment by haasn** [comment]
While you can take an SDR signal and put it into an HDR color space, it will not be expanded to fill the full dynamic range of the output. *Tone mapping* only goes in the one direction (HDR -> SDR), and I'm not sure the reverse is even reasonable.

**Comment by Manouchehri** [comment]
The main use-case I see is if you have mostly HDR content, but need to mix in a few SDR clips. =)

**Comment by haasn** [comment]
This was added in libplacebo v4.192, using the BT.2446A curves (among some others)
